//! Bonds file parser (port of `util/BondsParser.scala`).
//!
//! The genesis ceremony uses a bonds file of `<public_key> <stake>` lines to set the initial
//! validator set.

use std::collections::BTreeMap;
use std::path::Path;

use rchain_crypto::public_key::PublicKey;
use rchain_crypto::signatures::secp256k1::Secp256k1;
use rchain_crypto::signatures::signatures_alg::SignaturesAlg;
use rchain_shared::base16;
use rchain_shared::refined::NonNegI64;

/// Parse a bonds file into a validator → stake map (port of `BondsParser.parse`).
pub fn parse(path: &Path) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("FAILED PARSING BONDS FILE: {}\n{}", path.display(), e))?;
    let mut bonds = BTreeMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (pk_str, stake_str) = line.split_once(' ').ok_or_else(|| {
            format!("INVALID LINE FORMAT: `<public_key> <stake>`, actual: `{line}`")
        })?;
        let pk_bytes =
            base16::decode(pk_str).ok_or_else(|| format!("INVALID PUBLIC KEY: `{pk_str}`"))?;
        let stake: i64 = stake_str.parse().map_err(|_| {
            format!("INVALID STAKE `{stake_str}`. Please put a non-negative number.")
        })?;
        let stake = NonNegI64::try_from(stake)
            .map_err(|_| format!("NEGATIVE STAKE `{stake_str}`. Stake must be non-negative."))?;
        bonds.insert(PublicKey::new(pk_bytes), stake);
    }
    Ok(bonds)
}

/// Parse a bonds file, generating a fresh validator set if the file does not exist (port of
/// `BondsParser.parse(path, autogenShardSize)`).
pub fn parse_or_generate(
    path: &Path,
    autogen_shard_size: i32,
) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    match parse(path) {
        Ok(bonds) => Ok(bonds),
        Err(_) => new_validators(autogen_shard_size, path),
    }
}

/// Generate `autogen_shard_size` validators and write their keys + bonds file (port of
/// `newValidators`).
pub fn new_validators(
    autogen_shard_size: i32,
    bonds_file_path: &Path,
) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    let mut bonds = BTreeMap::new();
    for i in 0..autogen_shard_size {
        let (sec, pub_key) = Secp256k1.new_key_pair();
        // Write `<public_key>.sk` file with the private key (owner-only perms: it is secret).
        if let Some(parent) = bonds_file_path.parent() {
            let sk_file = parent.join(format!("{}.sk", base16::encode(pub_key.bytes())));
            let _ = rchain_crypto::util::key_util::write_private_key(
                &sk_file,
                base16::encode(sec.bytes()),
            );
        }
        // `i >= 0`, so `i + 1 >= 1` is non-negative by construction.
        let stake = NonNegI64::try_from(i64::from(i) + 1)
            .map_err(|_| "autogenerated stake is non-negative".to_string())?;
        bonds.insert(pub_key, stake);
    }

    let mut content = String::new();
    for (pk, stake) in &bonds {
        content.push_str(&format!(
            "{} {}\n",
            base16::encode(pk.bytes()),
            i64::from(*stake)
        ));
    }
    let _ = std::fs::write(bonds_file_path, content);
    Ok(bonds)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_bonds_file() {
        let dir = std::env::temp_dir().join(format!("rchain-bonds-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bonds.txt");
        std::fs::write(
            &path,
            "04c591a8ff19ac9c4e4e5793673b83123437e975285e7b442f4ee2654dffca5e2d2103ed494718c697ac9aebcfd19612e224db46661011863ed2fc54e71861e2a6 100\n\
             04c591a8ff19ac9c4e4e5793673b83123437e975285e7b442f4ee2654dffca5e2d2103ed494718c697ac9aebcfd19612e224db46661011863ed2fc54e71861e2a6 200\n",
        )
        .unwrap();

        let bonds = parse(&path).unwrap();
        // Duplicate keys collapse to the last stake.
        assert_eq!(bonds.len(), 1);
        assert_eq!(
            bonds.values().next().copied(),
            Some(200.try_into().unwrap())
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parses_bonds_file_rejects_bad_format() {
        let dir = std::env::temp_dir().join(format!("rchain-bonds-bad-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bonds.txt");
        std::fs::write(&path, "garbage line without spaces\n").unwrap();

        assert!(parse(&path).is_err());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
