//! Routing protocol wire types (generated by prost, re-exported for `comm`).

pub use crate::proto::routing::*;

#[cfg(test)]
mod tests {
    use prost::Message as _;

    use super::*;

    #[test]
    fn packet_round_trips() {
        let packet = Packet {
            type_id: "BlockMessage".to_string(),
            content: vec![1, 2, 3],
        };
        let bytes = packet.encode_to_vec();
        let decoded = Packet::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded, packet);
    }

    #[test]
    fn protocol_handshake_round_trips() {
        let protocol = Protocol {
            header: Some(Header {
                sender: Some(Node {
                    id: vec![1],
                    host: vec![127, 0, 0, 1],
                    tcp_port: 40400,
                    udp_port: 40404,
                }),
                network_id: "testnet".to_string(),
            }),
            message: Some(protocol::Message::ProtocolHandshake(ProtocolHandshake {
                nonce: vec![9, 9, 9],
            })),
        };
        let bytes = protocol.encode_to_vec();
        let decoded = Protocol::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded, protocol);
    }
}
