import Rchain.Syntax
import Rchain.Surface
import Rchain.Print
import Rchain.Parse
import Rchain.Par
import Rchain.Cmp
import Rchain.Rho
import Rchain.Sort
import Rchain.Ty
import Rchain.Subst
import Rchain.Reduce
import Rchain.Match
import Rchain.Merging
import Rchain.Silence
import Rchain.Store
import Rchain.Protocol
import Rchain.Json
import Rchain.Envelope
import Rchain.Lex
import Rchain.Concurrent
import Rchain.Tree
import Rchain.FreeVars
import Rchain.Effect
import Rchain.Scheduler
import Rchain.SchedulerOnchain
import Rchain.CrossShard
import Rchain.RSpace.Join
import Rchain.RSpace.Comm
import Rchain.RSpace.Merge
import Rchain.RSpace.Merkle
import Rchain.Casper.Stake
import Rchain.Proto
import Rchain.Casper.Fringe
import Rchain.Casper.Validate
import Rchain.Pos
import Rchain.Charging
import Rchain.Crypto.Random
import Rchain.Crypto.Spec
-- The law register (`Rchain/Laws.lean`) is pure data with no imports: the catalog of every law, and the
-- rows `Rchain/LawsMain.lean` checks the tree against. (Its own count is `lawCeiling`, checked against
-- the rows at build time; a number written in a comment here is a number nothing checks.)
import Rchain.Laws
