//! Casper protocol domain types + wire conversion.
//!
//! Mirrors `models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala`. The scalapb
//! `*Proto` types (generated by prost from `proto/casper.proto`) are kept private; these hand-written
//! domain types are the public API and carry `from(&Proto)` / `to_proto(&self)`. Sorting for
//! deterministic serialization (Law 16) happens here, at the domain layer, using `BTreeSet`/`BTreeMap`
//! (see `BlockMessage::to_proto`).

use std::collections::BTreeMap;

use prost::Message as _;
use rchain_crypto::hash::blake2b256_hash::Blake2b256Hash;
use rchain_shared::refined::{BlockHeight, NonNegI64, SeqNum};
use rchain_shared::serialize::Serialize;

use crate::block::state_hash::StateHash;
use crate::block_hash::BlockHash;
use crate::casper::protocol::deploy_service::DeployInfo;
use crate::proto::casper::PCost as PCostProto;
use crate::proto::casper::*;
use crate::validator::Validator;
use rchain_shared::base16;

// -------------------------------------------------------------------------------------------------
// Cost
// -------------------------------------------------------------------------------------------------

/// Phantom/execution cost (port of `PCost`).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PCost {
    pub cost: u64,
}

impl PCost {
    pub fn from_proto(p: &PCostProto) -> Self {
        Self { cost: p.cost }
    }
    pub fn to_proto(&self) -> PCostProto {
        PCostProto { cost: self.cost }
    }
}

// -------------------------------------------------------------------------------------------------
// Deploy data
// -------------------------------------------------------------------------------------------------

/// Deploy data (port of the `DeployData` case class; the deployer/signature live in
/// [`SignedDeployData`]).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeployData {
    pub term: String,
    pub timestamp: i64,
    pub phlo_price: i64,
    pub phlo_limit: i64,
    pub valid_after_block_number: i64,
    pub shard_id: String,
}

impl DeployData {
    /// The total phlo charge (`phlo_limit * phlo_price`). Returns `None` on overflow rather than
    /// wrapping (a wrapped charge would bypass cost accounting). Computed in `i128` so the product
    /// cannot overflow before the `i64` range check.
    pub fn total_phlo_charge(&self) -> Option<i64> {
        let product = (self.phlo_limit as i128).checked_mul(self.phlo_price as i128)?;
        i64::try_from(product).ok()
    }

    fn from_proto_data(p: &DeployDataProto) -> Self {
        Self {
            term: p.term.clone(),
            timestamp: p.timestamp,
            phlo_price: p.phlo_price,
            phlo_limit: p.phlo_limit,
            valid_after_block_number: p.valid_after_block_number,
            shard_id: p.shard_id.clone(),
        }
    }

    fn to_proto_data(&self) -> DeployDataProto {
        DeployDataProto {
            term: self.term.clone(),
            timestamp: self.timestamp,
            phlo_price: self.phlo_price,
            phlo_limit: self.phlo_limit,
            valid_after_block_number: self.valid_after_block_number,
            shard_id: self.shard_id.clone(),
            ..DeployDataProto::default()
        }
    }
}

impl Serialize<DeployData> for DeployData {
    fn encode(a: &DeployData) -> Vec<u8> {
        a.to_proto_data().encode_to_vec()
    }

    fn decode(bytes: &[u8]) -> Result<DeployData, String> {
        DeployDataProto::decode(bytes)
            .map(|p| DeployData::from_proto_data(&p))
            .map_err(|e| e.to_string())
    }
}

/// A signed deploy (the wire form of `Signed[DeployData]`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SignedDeployData {
    pub data: DeployData,
    pub deployer: Vec<u8>,
    pub sig: Vec<u8>,
    pub sig_algorithm: String,
}

impl SignedDeployData {
    pub fn from_proto(p: &DeployDataProto) -> Self {
        SignedDeployData {
            data: DeployData::from_proto_data(p),
            deployer: p.deployer.clone(),
            sig: p.sig.clone(),
            sig_algorithm: p.sig_algorithm.clone(),
        }
    }

    pub fn to_proto(&self) -> DeployDataProto {
        DeployDataProto {
            deployer: self.deployer.clone(),
            sig: self.sig.clone(),
            sig_algorithm: self.sig_algorithm.clone(),
            ..self.data.to_proto_data()
        }
    }

    /// Verify the signature over the deploy data, byte-identical to the HTTP path
    /// (`node/src/api/conversion.rs::to_signed_deploy`). Returns `false` on any failure
    /// (unknown algorithm, malformed key/sig, or mismatched signature).
    pub fn verify_signature(&self) -> bool {
        let Some(alg) =
            rchain_crypto::signatures::signatures_alg::from_algorithm(&self.sig_algorithm)
        else {
            return false;
        };
        let serialized = <DeployData as Serialize<DeployData>>::encode(&self.data);
        let hash = rchain_crypto::signatures::signed::signature_hash(alg.name(), &serialized);
        let pk = rchain_crypto::public_key::PublicKey::new(self.deployer.clone());
        alg.verify(&hash, &self.sig, pk.bytes())
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = DeployDataProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(Self::from_proto(&proto))
    }
}

// -------------------------------------------------------------------------------------------------
// Events
// -------------------------------------------------------------------------------------------------

/// A peek event (port of `Peek`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Peek {
    pub channel_index: i32,
}

/// A produce event (port of `ProduceEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProduceEvent {
    pub channels_hash: Vec<u8>,
    pub hash: Vec<u8>,
    pub persistent: bool,
    pub times_repeated: i32,
}

/// A consume event (port of `ConsumeEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConsumeEvent {
    pub channels_hashes: Vec<Vec<u8>>,
    pub hash: Vec<u8>,
    pub persistent: bool,
}

/// A comm event (port of `CommEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CommEvent {
    pub consume: ConsumeEvent,
    pub produces: Vec<ProduceEvent>,
    pub peeks: Vec<Peek>,
}

/// An execution-trace event (port of the sealed `Event`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Event {
    Produce(ProduceEvent),
    Consume(ConsumeEvent),
    Comm(CommEvent),
}

impl Event {
    pub fn from_proto(e: &EventProto) -> Result<Event, crate::errors::ModelsError> {
        match &e.event_instance {
            Some(event_proto::EventInstance::Produce(pe)) => Ok(Event::Produce(ProduceEvent {
                channels_hash: pe.channels_hash.clone(),
                hash: pe.hash.clone(),
                persistent: pe.persistent,
                times_repeated: pe.times_repeated,
            })),
            Some(event_proto::EventInstance::Consume(ce)) => Ok(Event::Consume(ConsumeEvent {
                channels_hashes: ce.channels_hashes.clone(),
                hash: ce.hash.clone(),
                persistent: ce.persistent,
            })),
            Some(event_proto::EventInstance::Comm(ce)) => {
                let consume = ce
                    .consume
                    .as_ref()
                    .ok_or(crate::errors::ModelsError::Malformed(
                        "malformed CommEvent: missing consume",
                    ))?;
                Ok(Event::Comm(CommEvent {
                    consume: ConsumeEvent {
                        channels_hashes: consume.channels_hashes.clone(),
                        hash: consume.hash.clone(),
                        persistent: consume.persistent,
                    },
                    produces: ce
                        .produces
                        .iter()
                        .map(|p| ProduceEvent {
                            channels_hash: p.channels_hash.clone(),
                            hash: p.hash.clone(),
                            persistent: p.persistent,
                            times_repeated: p.times_repeated,
                        })
                        .collect(),
                    peeks: ce
                        .peeks
                        .iter()
                        .map(|p| Peek {
                            channel_index: p.channel_index,
                        })
                        .collect(),
                }))
            }
            None => Err(crate::errors::ModelsError::Malformed(
                "malformed Event: empty",
            )),
        }
    }

    pub fn to_proto(&self) -> EventProto {
        match self {
            Event::Produce(pe) => EventProto {
                event_instance: Some(event_proto::EventInstance::Produce(ProduceEventProto {
                    channels_hash: pe.channels_hash.clone(),
                    hash: pe.hash.clone(),
                    persistent: pe.persistent,
                    times_repeated: pe.times_repeated,
                })),
            },
            Event::Consume(ce) => EventProto {
                event_instance: Some(event_proto::EventInstance::Consume(ConsumeEventProto {
                    channels_hashes: ce.channels_hashes.clone(),
                    hash: ce.hash.clone(),
                    persistent: ce.persistent,
                })),
            },
            Event::Comm(ce) => EventProto {
                event_instance: Some(event_proto::EventInstance::Comm(CommEventProto {
                    consume: Some(ConsumeEventProto {
                        channels_hashes: ce.consume.channels_hashes.clone(),
                        hash: ce.consume.hash.clone(),
                        persistent: ce.consume.persistent,
                    }),
                    produces: ce
                        .produces
                        .iter()
                        .map(|p| ProduceEventProto {
                            channels_hash: p.channels_hash.clone(),
                            hash: p.hash.clone(),
                            persistent: p.persistent,
                            times_repeated: p.times_repeated,
                        })
                        .collect(),
                    peeks: ce
                        .peeks
                        .iter()
                        .map(|p| PeekProto {
                            channel_index: p.channel_index,
                        })
                        .collect(),
                })),
            },
        }
    }
}

// -------------------------------------------------------------------------------------------------
// System deploys
// -------------------------------------------------------------------------------------------------

/// System deploy data (port of the sealed `SystemDeployData`).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SystemDeployData {
    Slash(Validator),
    CloseBlock,
    Empty,
}

impl SystemDeployData {
    pub fn from_proto(p: &SystemDeployDataProto) -> Result<Self, crate::errors::ModelsError> {
        match &p.system_deploy {
            Some(system_deploy_data_proto::SystemDeploy::SlashSystemDeploy(sd)) => Ok(
                SystemDeployData::Slash(Validator::try_from(sd.slashed_validator.as_slice())?),
            ),
            Some(system_deploy_data_proto::SystemDeploy::CloseBlockSystemDeploy(_)) => {
                Ok(SystemDeployData::CloseBlock)
            }
            None => Ok(SystemDeployData::Empty),
        }
    }

    pub fn to_proto(&self) -> SystemDeployDataProto {
        match self {
            SystemDeployData::Slash(validator) => SystemDeployDataProto {
                system_deploy: Some(system_deploy_data_proto::SystemDeploy::SlashSystemDeploy(
                    SlashSystemDeployDataProto {
                        slashed_validator: validator.as_bytes().to_vec(),
                    },
                )),
            },
            SystemDeployData::CloseBlock => SystemDeployDataProto {
                system_deploy: Some(
                    system_deploy_data_proto::SystemDeploy::CloseBlockSystemDeploy(
                        CloseBlockSystemDeployDataProto {},
                    ),
                ),
            },
            SystemDeployData::Empty => SystemDeployDataProto {
                system_deploy: None,
            },
        }
    }
}

/// A processed system deploy (port of the sealed `ProcessedSystemDeploy`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProcessedSystemDeploy {
    Succeeded {
        event_list: Vec<Event>,
        system_deploy: SystemDeployData,
    },
    Failed {
        event_list: Vec<Event>,
        error_msg: String,
    },
}

impl ProcessedSystemDeploy {
    pub fn from_proto(p: &ProcessedSystemDeployProto) -> Result<Self, crate::errors::ModelsError> {
        let deploy_log: Result<Vec<Event>, crate::errors::ModelsError> =
            p.deploy_log.iter().map(Event::from_proto).collect();
        let deploy_log = deploy_log?;
        if p.error_msg.is_empty() {
            let system_deploy = match p.system_deploy.as_ref() {
                Some(sd) => SystemDeployData::from_proto(sd)?,
                None => SystemDeployData::Empty,
            };
            Ok(ProcessedSystemDeploy::Succeeded {
                event_list: deploy_log,
                system_deploy,
            })
        } else {
            Ok(ProcessedSystemDeploy::Failed {
                event_list: deploy_log,
                error_msg: p.error_msg.clone(),
            })
        }
    }

    pub fn to_proto(&self) -> ProcessedSystemDeployProto {
        match self {
            ProcessedSystemDeploy::Succeeded {
                event_list,
                system_deploy,
            } => ProcessedSystemDeployProto {
                system_deploy: Some(system_deploy.to_proto()),
                deploy_log: event_list.iter().map(Event::to_proto).collect(),
                error_msg: String::new(),
            },
            ProcessedSystemDeploy::Failed {
                event_list,
                error_msg,
            } => ProcessedSystemDeployProto {
                system_deploy: None,
                deploy_log: event_list.iter().map(Event::to_proto).collect(),
                error_msg: error_msg.clone(),
            },
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Rholang state
// -------------------------------------------------------------------------------------------------

/// A processed deploy (port of `ProcessedDeploy`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProcessedDeploy {
    pub deploy: SignedDeployData,
    pub cost: PCost,
    pub deploy_log: Vec<Event>,
    pub is_failed: bool,
    pub system_deploy_error: Option<String>,
}

impl ProcessedDeploy {
    pub fn from_proto(p: &ProcessedDeployProto) -> Result<Self, crate::errors::ModelsError> {
        let deploy = p
            .deploy
            .as_ref()
            .ok_or(crate::errors::ModelsError::Malformed(
                "malformed ProcessedDeploy: missing deploy",
            ))?;
        let deploy_log: Result<Vec<Event>, crate::errors::ModelsError> =
            p.deploy_log.iter().map(Event::from_proto).collect();
        Ok(ProcessedDeploy {
            deploy: SignedDeployData::from_proto(deploy),
            cost: p.cost.as_ref().map(PCost::from_proto).unwrap_or_default(),
            deploy_log: deploy_log?,
            is_failed: p.errored,
            system_deploy_error: if p.system_deploy_error.is_empty() {
                None
            } else {
                Some(p.system_deploy_error.clone())
            },
        })
    }

    pub fn to_proto(&self) -> ProcessedDeployProto {
        ProcessedDeployProto {
            deploy: Some(self.deploy.to_proto()),
            cost: Some(self.cost.to_proto()),
            deploy_log: self.deploy_log.iter().map(Event::to_proto).collect(),
            errored: self.is_failed,
            system_deploy_error: self.system_deploy_error.clone().unwrap_or_default(),
        }
    }

    /// Build the client-facing deploy info (port of `toDeployInfo`).
    pub fn to_deploy_info(&self) -> DeployInfo {
        DeployInfo {
            deployer: base16::encode(&self.deploy.deployer),
            term: self.deploy.data.term.clone(),
            timestamp: self.deploy.data.timestamp,
            sig: base16::encode(&self.deploy.sig),
            sig_algorithm: self.deploy.sig_algorithm.clone(),
            phlo_price: self.deploy.data.phlo_price,
            phlo_limit: self.deploy.data.phlo_limit,
            valid_after_block_number: self.deploy.data.valid_after_block_number,
            cost: self.cost.cost,
            errored: self.is_failed,
            system_deploy_error: self.system_deploy_error.clone().unwrap_or_default(),
        }
    }

    /// The phlo refunded after this deploy: `max(0, phlo_limit − cost) × phlo_price` (port of
    /// `ProcessedDeploy.refundAmount`). Computed in `i128` and clamped to `i64::MAX` so the refund
    /// cannot wrap (it is non-negative by construction). Shared by play and replay so the two paths
    /// cannot drift (S3).
    pub fn refund_amount(&self) -> i64 {
        let remaining = self
            .deploy
            .data
            .phlo_limit
            .saturating_sub_unsigned(self.cost.cost)
            .max(0) as i128;
        let product = remaining * (self.deploy.data.phlo_price as i128);
        i64::try_from(product).unwrap_or(i64::MAX)
    }
}

/// Rholang tuple-space state change (port of `RholangState`).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RholangState {
    pub deploys: Vec<ProcessedDeploy>,
    pub system_deploys: Vec<ProcessedSystemDeploy>,
}

impl RholangState {
    pub fn from_proto(p: &RholangStateProto) -> Result<Self, crate::errors::ModelsError> {
        let deploys: Result<Vec<ProcessedDeploy>, crate::errors::ModelsError> =
            p.deploys.iter().map(ProcessedDeploy::from_proto).collect();
        let system_deploys: Result<Vec<ProcessedSystemDeploy>, crate::errors::ModelsError> = p
            .system_deploys
            .iter()
            .map(ProcessedSystemDeploy::from_proto)
            .collect();
        Ok(RholangState {
            deploys: deploys?,
            system_deploys: system_deploys?,
        })
    }

    pub fn to_proto(&self) -> RholangStateProto {
        RholangStateProto {
            deploys: self.deploys.iter().map(ProcessedDeploy::to_proto).collect(),
            system_deploys: self
                .system_deploys
                .iter()
                .map(ProcessedSystemDeploy::to_proto)
                .collect(),
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Block message
// -------------------------------------------------------------------------------------------------

/// A block message (port of `BlockMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockMessage {
    pub version: i32,
    pub shard_id: String,
    pub block_hash: BlockHash,
    pub block_number: BlockHeight,
    pub sender: Validator,
    pub seq_num: SeqNum,
    pub pre_state_hash: StateHash,
    pub post_state_hash: StateHash,
    pub justifications: Vec<BlockHash>,
    pub bonds: BTreeMap<Validator, NonNegI64>,
    pub rejected_deploys: std::collections::BTreeSet<Vec<u8>>,
    pub rejected_blocks: std::collections::BTreeSet<BlockHash>,
    pub rejected_senders: std::collections::BTreeSet<Vec<u8>>,
    pub state: RholangState,
    pub sig_algorithm: String,
    pub sig: Vec<u8>,
}

impl BlockMessage {
    pub fn from_proto(bm: &BlockMessageProto) -> Result<BlockMessage, crate::errors::ModelsError> {
        let state = bm
            .state
            .as_ref()
            .ok_or(crate::errors::ModelsError::Malformed(
                "malformed BlockMessage: missing state",
            ))?;
        Ok(BlockMessage {
            version: bm.version,
            shard_id: bm.shard_id.clone(),
            block_hash: BlockHash::try_from(bm.block_hash.as_slice())?,
            block_number: BlockHeight::try_from(bm.block_number)
                .map_err(|_| crate::errors::ModelsError::Malformed("negative block number"))?,
            sender: Validator::try_from(bm.sender.as_slice())?,
            seq_num: SeqNum::try_from(bm.seq_num)
                .map_err(|_| crate::errors::ModelsError::Malformed("negative sequence number"))?,
            pre_state_hash: StateHash::try_from(bm.pre_state_hash.as_slice())?,
            post_state_hash: StateHash::try_from(bm.post_state_hash.as_slice())?,
            justifications: bm
                .justifications
                .iter()
                .map(|b| BlockHash::try_from(b.as_slice()))
                .collect::<Result<Vec<BlockHash>, crate::errors::ModelsError>>()?,
            bonds: bm
                .bonds
                .iter()
                .map(|b| {
                    let stake = NonNegI64::try_from(b.stake)
                        .map_err(|_| crate::errors::ModelsError::Malformed("negative bond stake"))?;
                    Ok((Validator::try_from(b.validator.as_slice())?, stake))
                })
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            rejected_deploys: bm.rejected_deploys.iter().cloned().collect(),
            rejected_blocks: bm
                .rejected_blocks
                .iter()
                .map(|b| BlockHash::try_from(b.as_slice()))
                .collect::<Result<std::collections::BTreeSet<BlockHash>, crate::errors::ModelsError>>()?,
            rejected_senders: bm.rejected_senders.iter().cloned().collect(),
            state: RholangState::from_proto(state)?,
            sig_algorithm: bm.sig_algorithm.clone(),
            sig: bm.sig.clone(),
        })
    }

    /// Serialize with sorted justifications/bonds/rejections (Law 16 determinism).
    pub fn to_proto(&self) -> BlockMessageProto {
        let mut justifications: Vec<BlockHash> = self.justifications.clone();
        justifications.sort();
        let mut bonds: Vec<BondProto> = self
            .bonds
            .iter()
            .map(|(validator, stake)| BondProto {
                validator: validator.as_bytes().to_vec(),
                stake: i64::from(*stake),
            })
            .collect();
        bonds.sort_by(|a, b| a.validator.cmp(&b.validator));
        let mut rejected_deploys: Vec<Vec<u8>> = self.rejected_deploys.iter().cloned().collect();
        rejected_deploys.sort();
        let mut rejected_blocks: Vec<BlockHash> = self.rejected_blocks.iter().copied().collect();
        rejected_blocks.sort();
        let mut rejected_senders: Vec<Vec<u8>> = self.rejected_senders.iter().cloned().collect();
        rejected_senders.sort();

        BlockMessageProto {
            version: self.version,
            shard_id: self.shard_id.clone(),
            block_hash: self.block_hash.as_bytes().to_vec(),
            block_number: i64::from(self.block_number),
            sender: self.sender.as_bytes().to_vec(),
            seq_num: i64::from(self.seq_num),
            pre_state_hash: self.pre_state_hash.as_bytes().to_vec(),
            post_state_hash: self.post_state_hash.as_bytes().to_vec(),
            justifications: justifications
                .into_iter()
                .map(|b| b.as_bytes().to_vec())
                .collect(),
            bonds,
            rejected_deploys,
            rejected_blocks: rejected_blocks
                .into_iter()
                .map(|b| b.as_bytes().to_vec())
                .collect(),
            rejected_senders,
            state: Some(self.state.to_proto()),
            sig_algorithm: self.sig_algorithm.clone(),
            sig: self.sig.clone(),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<BlockMessage, crate::errors::ModelsError> {
        let proto = BlockMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockMessage::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Approved block + tips + request messages
// -------------------------------------------------------------------------------------------------

/// A finalized fringe (port of `FinalizedFringe`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FinalizedFringe {
    pub hashes: Vec<BlockHash>,
    pub state_hash: StateHash,
}

impl FinalizedFringe {
    pub fn from_proto(f: &FinalizedFringeProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(FinalizedFringe {
            hashes: f
                .hashes
                .iter()
                .map(|h| BlockHash::try_from(h.as_slice()))
                .collect::<Result<Vec<BlockHash>, crate::errors::ModelsError>>()?,
            state_hash: StateHash::try_from(f.state_hash.as_slice())?,
        })
    }
    pub fn to_proto(&self) -> FinalizedFringeProto {
        FinalizedFringeProto {
            hashes: self.hashes.iter().map(|h| h.as_bytes().to_vec()).collect(),
            state_hash: self.state_hash.as_bytes().to_vec(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = FinalizedFringeProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        FinalizedFringe::from_proto(&proto)
    }
}

/// A finalized-fringe request (port of `FinalizedFringeRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FinalizedFringeRequest {
    pub identifier: String,
    pub trim_state: bool,
}

/// A fork-choice tip request (port of `ForkChoiceTipRequest`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ForkChoiceTipRequest;

/// A has-block request (port of `HasBlockRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HasBlockRequest {
    pub hash: Vec<u8>,
}

/// A has-block response (port of `HasBlock`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HasBlock {
    pub hash: Vec<u8>,
}

/// A block request (port of `BlockRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockRequest {
    pub hash: Vec<u8>,
}

/// A block-hash message (port of `BlockHashMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockHashMessage {
    pub block_hash: BlockHash,
    pub block_creator: Vec<u8>,
}

impl FinalizedFringeRequest {
    pub fn from_proto(m: &FinalizedFringeRequestProto) -> Self {
        FinalizedFringeRequest {
            identifier: m.identifier.clone(),
            trim_state: m.trim_state,
        }
    }
    pub fn to_proto(&self) -> FinalizedFringeRequestProto {
        FinalizedFringeRequestProto {
            identifier: self.identifier.clone(),
            trim_state: self.trim_state,
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = FinalizedFringeRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(FinalizedFringeRequest::from_proto(&proto))
    }
}

impl ForkChoiceTipRequest {
    pub fn to_proto(&self) -> ForkChoiceTipRequestProto {
        ForkChoiceTipRequestProto {}
    }
    pub fn from_proto(_m: &ForkChoiceTipRequestProto) -> Self {
        ForkChoiceTipRequest
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = ForkChoiceTipRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(ForkChoiceTipRequest::from_proto(&proto))
    }
}

impl HasBlockRequest {
    pub fn from_proto(m: &HasBlockRequestProto) -> Self {
        HasBlockRequest {
            hash: m.hash.clone(),
        }
    }
    pub fn to_proto(&self) -> HasBlockRequestProto {
        HasBlockRequestProto {
            hash: self.hash.clone(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = HasBlockRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(HasBlockRequest::from_proto(&proto))
    }
}

impl HasBlock {
    pub fn from_proto(m: &HasBlockProto) -> Self {
        HasBlock {
            hash: m.hash.clone(),
        }
    }
    pub fn to_proto(&self) -> HasBlockProto {
        HasBlockProto {
            hash: self.hash.clone(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = HasBlockProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(HasBlock::from_proto(&proto))
    }
}

impl BlockRequest {
    pub fn from_proto(m: &BlockRequestProto) -> Self {
        BlockRequest {
            hash: m.hash.clone(),
        }
    }
    pub fn to_proto(&self) -> BlockRequestProto {
        BlockRequestProto {
            hash: self.hash.clone(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(BlockRequest::from_proto(&proto))
    }
}

impl BlockHashMessage {
    pub fn from_proto(m: &BlockHashMessageProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(BlockHashMessage {
            block_hash: BlockHash::try_from(m.hash.as_slice())?,
            block_creator: m.block_creator.clone(),
        })
    }
    pub fn to_proto(&self) -> BlockHashMessageProto {
        BlockHashMessageProto {
            hash: self.block_hash.as_bytes().to_vec(),
            block_creator: self.block_creator.clone(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockHashMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockHashMessage::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Store items (last finalized state)
// -------------------------------------------------------------------------------------------------

/// The non-existent store-node index encoding (port of `StoreNodeKey.noneIndex`).
const STORE_NODE_KEY_NONE_INDEX: i32 = 0x100;

/// Decode a `(hash, index)` store-node key (port of `StoreNodeKey.from`).
fn store_node_key_from_proto(
    s: &StoreNodeKeyProto,
) -> Result<(Blake2b256Hash, Option<u8>), crate::errors::ModelsError> {
    let hash = Blake2b256Hash::try_from(s.hash.as_slice())?;
    let idx = if s.index == STORE_NODE_KEY_NONE_INDEX {
        None
    } else {
        // Validate-on-ingress: reject an out-of-range index rather than truncating via `as u8`.
        Some(u8::try_from(s.index).map_err(|_| {
            crate::errors::ModelsError::Malformed("store node key index out of range")
        })?)
    };
    Ok((hash, idx))
}

/// Encode a `(hash, index)` store-node key (port of `StoreNodeKey.toProto`).
fn store_node_key_to_proto(s: &(Blake2b256Hash, Option<u8>)) -> StoreNodeKeyProto {
    StoreNodeKeyProto {
        hash: s.0.as_bytes().to_vec(),
        index: s.1.map(|b| b as i32).unwrap_or(STORE_NODE_KEY_NONE_INDEX),
    }
}

/// A store-items request (port of `StoreItemsMessageRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoreItemsMessageRequest {
    pub start_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub skip: i32,
    pub take: i32,
}

impl StoreItemsMessageRequest {
    pub fn from_proto(
        m: &StoreItemsMessageRequestProto,
    ) -> Result<Self, crate::errors::ModelsError> {
        Ok(StoreItemsMessageRequest {
            start_path: m
                .start_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            skip: m.skip,
            take: m.take,
        })
    }
    pub fn to_proto(&self) -> StoreItemsMessageRequestProto {
        StoreItemsMessageRequestProto {
            start_path: self
                .start_path
                .iter()
                .map(store_node_key_to_proto)
                .collect(),
            skip: self.skip,
            take: self.take,
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = StoreItemsMessageRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Self::from_proto(&proto)
    }
}

/// A store-items response (port of `StoreItemsMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoreItemsMessage {
    pub start_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub last_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub history_items: Vec<(Blake2b256Hash, Vec<u8>)>,
    pub data_items: Vec<(Blake2b256Hash, Vec<u8>)>,
}

impl StoreItemsMessage {
    pub fn from_proto(m: &StoreItemsMessageProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(StoreItemsMessage {
            start_path: m
                .start_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            last_path: m
                .last_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            history_items: m
                .history_items
                .iter()
                .map(|y| Ok((Blake2b256Hash::try_from(y.key.as_slice())?, y.value.clone())))
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            data_items: m
                .data_items
                .iter()
                .map(|y| Ok((Blake2b256Hash::try_from(y.key.as_slice())?, y.value.clone())))
                .collect::<Result<_, crate::errors::ModelsError>>()?,
        })
    }
    pub fn to_proto(&self) -> StoreItemsMessageProto {
        StoreItemsMessageProto {
            start_path: self
                .start_path
                .iter()
                .map(store_node_key_to_proto)
                .collect(),
            last_path: self.last_path.iter().map(store_node_key_to_proto).collect(),
            history_items: self
                .history_items
                .iter()
                .map(|(k, v)| StoreItemProto {
                    key: k.as_bytes().to_vec(),
                    value: v.clone(),
                })
                .collect(),
            data_items: self
                .data_items
                .iter()
                .map(|(k, v)| StoreItemProto {
                    key: k.as_bytes().to_vec(),
                    value: v.clone(),
                })
                .collect(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = StoreItemsMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Self::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Casper message (sum type)
// -------------------------------------------------------------------------------------------------

/// The sealed `CasperMessage` sum type (port of the Scala `sealed trait CasperMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CasperMessage {
    BlockMessage(BlockMessage),
    BlockRequest(BlockRequest),
    BlockHashMessage(BlockHashMessage),
    HasBlock(HasBlock),
    HasBlockRequest(HasBlockRequest),
    ForkChoiceTipRequest(ForkChoiceTipRequest),
    FinalizedFringe(FinalizedFringe),
    FinalizedFringeRequest(FinalizedFringeRequest),
    StoreItemsMessageRequest(StoreItemsMessageRequest),
    StoreItemsMessage(StoreItemsMessage),
}

/// The sealed `CasperMessageProto` sum type (the scalapb `sealed trait CasperMessageProto`).
#[derive(Clone, Debug, PartialEq)]
pub enum CasperMessageProto {
    BlockMessage(BlockMessageProto),
    BlockRequest(BlockRequestProto),
    BlockHashMessage(BlockHashMessageProto),
    HasBlock(HasBlockProto),
    HasBlockRequest(HasBlockRequestProto),
    ForkChoiceTipRequest(ForkChoiceTipRequestProto),
    FinalizedFringe(FinalizedFringeProto),
    FinalizedFringeRequest(FinalizedFringeRequestProto),
    StoreItemsMessageRequest(StoreItemsMessageRequestProto),
    StoreItemsMessage(StoreItemsMessageProto),
}

impl CasperMessage {
    pub fn from_proto(
        cm: &CasperMessageProto,
    ) -> Result<CasperMessage, crate::errors::ModelsError> {
        match cm {
            CasperMessageProto::BlockMessage(m) => {
                Ok(CasperMessage::BlockMessage(BlockMessage::from_proto(m)?))
            }
            CasperMessageProto::BlockRequest(m) => Ok(CasperMessage::BlockRequest(BlockRequest {
                hash: m.hash.clone(),
            })),
            CasperMessageProto::BlockHashMessage(m) => Ok(CasperMessage::BlockHashMessage(
                BlockHashMessage::from_proto(m)?,
            )),
            CasperMessageProto::HasBlock(m) => Ok(CasperMessage::HasBlock(HasBlock {
                hash: m.hash.clone(),
            })),
            CasperMessageProto::HasBlockRequest(m) => {
                Ok(CasperMessage::HasBlockRequest(HasBlockRequest {
                    hash: m.hash.clone(),
                }))
            }
            CasperMessageProto::ForkChoiceTipRequest(_) => {
                Ok(CasperMessage::ForkChoiceTipRequest(ForkChoiceTipRequest))
            }
            CasperMessageProto::FinalizedFringe(m) => Ok(CasperMessage::FinalizedFringe(
                FinalizedFringe::from_proto(m)?,
            )),
            CasperMessageProto::FinalizedFringeRequest(m) => Ok(
                CasperMessage::FinalizedFringeRequest(FinalizedFringeRequest {
                    identifier: m.identifier.clone(),
                    trim_state: m.trim_state,
                }),
            ),
            CasperMessageProto::StoreItemsMessageRequest(m) => Ok(
                CasperMessage::StoreItemsMessageRequest(StoreItemsMessageRequest::from_proto(m)?),
            ),
            CasperMessageProto::StoreItemsMessage(m) => Ok(CasperMessage::StoreItemsMessage(
                StoreItemsMessage::from_proto(m)?,
            )),
        }
    }

    pub fn to_proto(&self) -> CasperMessageProto {
        match self {
            CasperMessage::BlockMessage(m) => CasperMessageProto::BlockMessage(m.to_proto()),
            CasperMessage::BlockRequest(m) => CasperMessageProto::BlockRequest(BlockRequestProto {
                hash: m.hash.clone(),
            }),
            CasperMessage::BlockHashMessage(m) => {
                CasperMessageProto::BlockHashMessage(BlockHashMessageProto {
                    hash: m.block_hash.as_bytes().to_vec(),
                    block_creator: m.block_creator.clone(),
                })
            }
            CasperMessage::HasBlock(m) => CasperMessageProto::HasBlock(HasBlockProto {
                hash: m.hash.clone(),
            }),
            CasperMessage::HasBlockRequest(m) => {
                CasperMessageProto::HasBlockRequest(HasBlockRequestProto {
                    hash: m.hash.clone(),
                })
            }
            CasperMessage::ForkChoiceTipRequest(_) => {
                CasperMessageProto::ForkChoiceTipRequest(ForkChoiceTipRequestProto {})
            }
            CasperMessage::FinalizedFringe(m) => CasperMessageProto::FinalizedFringe(m.to_proto()),
            CasperMessage::FinalizedFringeRequest(m) => {
                CasperMessageProto::FinalizedFringeRequest(FinalizedFringeRequestProto {
                    identifier: m.identifier.clone(),
                    trim_state: m.trim_state,
                })
            }
            CasperMessage::StoreItemsMessageRequest(m) => {
                CasperMessageProto::StoreItemsMessageRequest(m.to_proto())
            }
            CasperMessage::StoreItemsMessage(m) => {
                CasperMessageProto::StoreItemsMessage(m.to_proto())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block_hash(byte: u8) -> BlockHash {
        BlockHash::new([byte; 32])
    }

    fn validator(byte: u8) -> Validator {
        Validator::new([byte; 65])
    }

    fn empty_block() -> BlockMessage {
        BlockMessage {
            version: 1,
            shard_id: "root".to_string(),
            block_hash: block_hash(0),
            block_number: 0.try_into().unwrap(),
            sender: validator(1),
            seq_num: 0.try_into().unwrap(),
            pre_state_hash: StateHash::new([0u8; 32]),
            post_state_hash: StateHash::new([0u8; 32]),
            justifications: Vec::new(),
            bonds: BTreeMap::new(),
            rejected_deploys: std::collections::BTreeSet::new(),
            rejected_blocks: std::collections::BTreeSet::new(),
            rejected_senders: std::collections::BTreeSet::new(),
            state: RholangState::default(),
            sig_algorithm: "secp256k1".to_string(),
            sig: Vec::new(),
        }
    }

    #[test]
    fn law16_to_proto_sorts_justifications() {
        let mut block = empty_block();
        block.justifications = vec![block_hash(3), block_hash(1), block_hash(2)];
        let proto = block.to_proto();
        assert_eq!(
            proto.justifications,
            vec![
                block_hash(1).as_bytes().to_vec(),
                block_hash(2).as_bytes().to_vec(),
                block_hash(3).as_bytes().to_vec(),
            ]
        );
    }

    #[test]
    fn law16_to_proto_sorts_bonds_and_rejections() {
        let mut block = empty_block();
        block.bonds = BTreeMap::from([
            (validator(3), 1.try_into().unwrap()),
            (validator(1), 2.try_into().unwrap()),
            (validator(2), 3.try_into().unwrap()),
        ]);
        block.rejected_blocks = [block_hash(9), block_hash(1)].into_iter().collect();
        let proto = block.to_proto();
        // Bonds already iterated in key order (BTreeMap) and then sorted by validator bytes.
        let validators: Vec<u8> = proto.bonds.iter().map(|b| b.validator[0]).collect();
        assert_eq!(validators, vec![1, 2, 3]);
        assert_eq!(
            proto.rejected_blocks,
            vec![
                block_hash(1).as_bytes().to_vec(),
                block_hash(9).as_bytes().to_vec()
            ]
        );
    }

    #[test]
    fn block_message_round_trips() {
        let mut block = empty_block();
        block.justifications = vec![block_hash(1), block_hash(2)];
        block.bonds = BTreeMap::from([(validator(1), 100.try_into().unwrap())]);
        block.rejected_blocks = [block_hash(7)].into_iter().collect();
        let bytes = block.to_bytes();
        let decoded = BlockMessage::from_bytes(&bytes).unwrap();
        assert_eq!(decoded, block);
    }

    #[test]
    fn finalized_fringe_round_trips() {
        let fringe = FinalizedFringe {
            hashes: vec![block_hash(1), block_hash(2)],
            state_hash: StateHash::new([7u8; 32]),
        };
        let decoded = FinalizedFringe::from_bytes(&fringe.to_bytes()).unwrap();
        assert_eq!(decoded, fringe);
    }

    #[test]
    fn casper_message_block_round_trips() {
        let msg = CasperMessage::BlockMessage(empty_block());
        let proto = msg.to_proto();
        let decoded = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded, msg);
    }

    #[test]
    fn store_items_message_round_trips() {
        let msg = StoreItemsMessage {
            start_path: vec![(Blake2b256Hash::from_bytes([1u8; 32]), None)],
            last_path: vec![(Blake2b256Hash::from_bytes([2u8; 32]), Some(3))],
            history_items: vec![(Blake2b256Hash::from_bytes([4u8; 32]), vec![5, 6])],
            data_items: vec![(Blake2b256Hash::from_bytes([7u8; 32]), vec![8])],
        };
        let decoded = StoreItemsMessage::from_bytes(&msg.to_bytes()).unwrap();
        assert_eq!(decoded, msg);

        let casper = CasperMessage::StoreItemsMessage(msg.clone());
        let proto = casper.to_proto();
        let decoded_casper = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded_casper, casper);
    }

    #[test]
    fn store_items_message_request_round_trips() {
        let req = StoreItemsMessageRequest {
            start_path: vec![(Blake2b256Hash::from_bytes([9u8; 32]), Some(1))],
            skip: 2,
            take: 3,
        };
        let decoded = StoreItemsMessageRequest::from_bytes(&req.to_bytes()).unwrap();
        assert_eq!(decoded, req);

        let casper = CasperMessage::StoreItemsMessageRequest(req.clone());
        let proto = casper.to_proto();
        let decoded_casper = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded_casper, casper);
    }

    fn signed_deploy_data(term: &str) -> SignedDeployData {
        use rchain_crypto::signatures::secp256k1::Secp256k1;
        use rchain_crypto::signatures::signatures_alg::SignaturesAlg;
        use rchain_crypto::signatures::signed::Signed;
        let (sec, _pk) = Secp256k1.new_key_pair();
        let data = DeployData {
            term: term.to_string(),
            timestamp: 0,
            phlo_price: 1,
            phlo_limit: 100,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
        };
        let signed = Signed::new(data, &Secp256k1, &sec).unwrap();
        SignedDeployData {
            data: signed.data,
            deployer: signed.pk.bytes().to_vec(),
            sig: signed.sig,
            sig_algorithm: signed.sig_algorithm.name().to_string(),
        }
    }

    #[test]
    fn verify_signature_accepts_valid_deploy() {
        assert!(signed_deploy_data("Nil").verify_signature());
    }

    #[test]
    fn verify_signature_rejects_tampered_term() {
        let mut sd = signed_deploy_data("Nil");
        sd.data.term = "Nil | Nil".to_string();
        assert!(!sd.verify_signature());
    }

    #[test]
    fn verify_signature_rejects_unknown_algorithm() {
        let mut sd = signed_deploy_data("Nil");
        sd.sig_algorithm = "bogus".to_string();
        assert!(!sd.verify_signature());
    }

    #[test]
    fn total_phlo_charge_does_not_wrap_on_overflow() {
        let mut d = DeployData {
            term: "Nil".to_string(),
            timestamp: 0,
            phlo_price: i64::MAX,
            phlo_limit: 2,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
        };
        assert_eq!(d.total_phlo_charge(), None);

        d.phlo_limit = 1;
        assert_eq!(d.total_phlo_charge(), Some(i64::MAX));

        d.phlo_limit = 0;
        assert_eq!(d.total_phlo_charge(), Some(0));
    }
}
