//! Casper protocol domain types + wire conversion.
//!
//! Mirrors `models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala`. The scalapb
//! `*Proto` types (generated by prost from `proto/casper.proto`) are kept private; these hand-written
//! domain types are the public API and carry `from(&Proto)` / `to_proto(&self)`. Sorting for
//! deterministic serialization (Law 16) happens here, at the domain layer, using `BTreeSet`/`BTreeMap`
//! (see `BlockMessage::to_proto`).

use std::collections::{BTreeMap, BTreeSet};

use prost::Message as _;
use rchain_crypto::hash::blake2b256_hash::Blake2b256Hash;
use rchain_shared::refined::{BlockHeight, NonNegI64, SeqNum};
use rchain_shared::serialize::Serialize;

use crate::block::state_hash::StateHash;
use crate::block_hash::BlockHash;
use crate::block_metadata::SlashSeverity;
use crate::casper::protocol::deploy_service::DeployInfo;
use crate::proto::casper::PCost as PCostProto;
use crate::proto::casper::*;
use crate::validator::Validator;
use rchain_shared::base16;

// -------------------------------------------------------------------------------------------------
// Cost
// -------------------------------------------------------------------------------------------------

/// Phantom/execution cost (port of `PCost`).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PCost {
    pub cost: u64,
}

impl PCost {
    pub fn from_proto(p: &PCostProto) -> Self {
        Self { cost: p.cost }
    }
    pub fn to_proto(&self) -> PCostProto {
        PCostProto { cost: self.cost }
    }
}

// -------------------------------------------------------------------------------------------------
// Deploy data
// -------------------------------------------------------------------------------------------------

/// Deploy data (port of the `DeployData` case class; the deployer/signature live in
/// [`SignedDeployData`]).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeployData {
    pub term: String,
    pub timestamp: i64,
    pub phlo_price: i64,
    pub phlo_limit: i64,
    pub valid_after_block_number: i64,
    pub shard_id: String,
    /// Binary attachments (RCHIP #39), hex-encoded in JSON. They are part of the signed deploy data
    /// and are exposed to rholang as `rho:attachment:1`, `rho:attachment:2`, … (1-based, yielding a
    /// `ByteArray`). Empty for an ordinary deploy — which still encodes exactly as before, so
    /// existing signatures and deploy ids are unchanged.
    #[serde(
        default,
        skip_serializing_if = "Vec::is_empty",
        with = "hex_attachments"
    )]
    pub attachments: Vec<Vec<u8>>,
}

/// Serde helper: attachments are hex strings in JSON, the API convention for bytes elsewhere
/// (`deployer`, `signature`, hashes).
mod hex_attachments {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(value: &[Vec<u8>], s: S) -> Result<S::Ok, S::Error> {
        let hex: Vec<String> = value
            .iter()
            .map(|bytes| rchain_shared::base16::encode(bytes))
            .collect();
        s.collect_seq(hex)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<Vec<u8>>, D::Error> {
        let hex = Vec::<String>::deserialize(d)?;
        hex.into_iter()
            .map(|h| {
                rchain_shared::base16::decode(&h)
                    .ok_or_else(|| serde::de::Error::custom("attachment is not valid hex"))
            })
            .collect()
    }
}

impl DeployData {
    /// The total phlo charge (`phlo_limit * phlo_price`). Returns `None` on overflow rather than
    /// wrapping (a wrapped charge would bypass cost accounting). Computed in `i128` so the product
    /// cannot overflow before the `i64` range check.
    ///
    /// **The sign is checked here, and this is the only place it can enter** (AUDIT C109). `phlo_limit`
    /// is `int64` on the wire (`casper.proto`, `DeployDataProto.phlo_limit`), and the charge is a
    /// *debit*: the amount flows to `native.pre_charge`, which subtracts it from the deployer's vault.
    /// A negative limit made that subtraction an **addition** — `balance - (-n) == balance + n` — so a
    /// deploy with `phlo_limit = -100, phlo_price = 1` credited its own deployer 100 REV out of
    /// nothing, while `credit_pos_vault` no-opped on the negative amount and left the staking vault
    /// untouched. The ingress guard at `casper::api::block_api_impl` caught the deploy path, but this
    /// function is what **block validation and replay** call, so a *peer's* block carried the negative
    /// limit straight through to the charge.
    ///
    /// Returning `Option<NonNegI64>` is the fix rather than adding a guard at each caller: the callers
    /// already treat `None` as a hard error ("phlo charge overflow"), the type carries the invariant to
    /// `pre_charge` and on into the vault arithmetic, and a negative limit is now unrepresentable one
    /// step after the wire instead of representable all the way to the balance.
    pub fn total_phlo_charge(&self) -> Option<NonNegI64> {
        let product = (self.phlo_limit as i128).checked_mul(self.phlo_price as i128)?;
        let charge = i64::try_from(product).ok()?;
        NonNegI64::try_from(charge).ok()
    }

    fn from_proto_data(p: &DeployDataProto) -> Self {
        Self {
            term: p.term.clone(),
            timestamp: p.timestamp,
            phlo_price: p.phlo_price,
            phlo_limit: p.phlo_limit,
            valid_after_block_number: p.valid_after_block_number,
            shard_id: p.shard_id.clone(),
            attachments: p.attachments.clone(),
        }
    }

    fn to_proto_data(&self) -> DeployDataProto {
        DeployDataProto {
            term: self.term.clone(),
            timestamp: self.timestamp,
            phlo_price: self.phlo_price,
            phlo_limit: self.phlo_limit,
            valid_after_block_number: self.valid_after_block_number,
            shard_id: self.shard_id.clone(),
            attachments: self.attachments.clone(),
            ..DeployDataProto::default()
        }
    }
}

impl Serialize<DeployData> for DeployData {
    fn encode(a: &DeployData) -> Vec<u8> {
        a.to_proto_data().encode_to_vec()
    }

    fn decode(bytes: &[u8]) -> Result<DeployData, String> {
        DeployDataProto::decode(bytes)
            .map(|p| DeployData::from_proto_data(&p))
            .map_err(|e| e.to_string())
    }
}

/// A signed deploy (the wire form of `Signed[DeployData]`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SignedDeployData {
    pub data: DeployData,
    pub deployer: Vec<u8>,
    pub sig: Vec<u8>,
    pub sig_algorithm: String,
}

impl SignedDeployData {
    pub fn from_proto(p: &DeployDataProto) -> Self {
        SignedDeployData {
            data: DeployData::from_proto_data(p),
            deployer: p.deployer.clone(),
            sig: p.sig.clone(),
            sig_algorithm: p.sig_algorithm.clone(),
        }
    }

    pub fn to_proto(&self) -> DeployDataProto {
        DeployDataProto {
            deployer: self.deployer.clone(),
            sig: self.sig.clone(),
            sig_algorithm: self.sig_algorithm.clone(),
            ..self.data.to_proto_data()
        }
    }

    /// Verify the signature over the deploy data, byte-identical to the HTTP path
    /// (`node/src/api/conversion.rs::to_signed_deploy`). Returns `false` on any failure
    /// (unknown algorithm, malformed key/sig, or mismatched signature).
    pub fn verify_signature(&self) -> bool {
        let Some(alg) =
            rchain_crypto::signatures::signatures_alg::from_algorithm(&self.sig_algorithm)
        else {
            return false;
        };
        let serialized = <DeployData as Serialize<DeployData>>::encode(&self.data);
        let hash = rchain_crypto::signatures::signed::signature_hash(alg.name(), &serialized);
        let pk = rchain_crypto::public_key::PublicKey::new(self.deployer.clone());
        alg.verify(&hash, &self.sig, pk.bytes())
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = DeployDataProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(Self::from_proto(&proto))
    }
}

// -------------------------------------------------------------------------------------------------
// Events
// -------------------------------------------------------------------------------------------------

/// A peek event (port of `Peek`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Peek {
    pub channel_index: i32,
}

/// A produce event (port of `ProduceEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProduceEvent {
    pub channels_hash: Vec<u8>,
    pub hash: Vec<u8>,
    pub persistent: bool,
    pub times_repeated: i32,
}

/// A consume event (port of `ConsumeEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConsumeEvent {
    pub channels_hashes: Vec<Vec<u8>>,
    pub hash: Vec<u8>,
    pub persistent: bool,
}

/// A comm event (port of `CommEvent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CommEvent {
    pub consume: ConsumeEvent,
    pub produces: Vec<ProduceEvent>,
    pub peeks: Vec<Peek>,
}

/// An execution-trace event (port of the sealed `Event`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Event {
    Produce(ProduceEvent),
    Consume(ConsumeEvent),
    Comm(CommEvent),
}

/// A 32-byte hash field off the wire.
///
/// `Event` is the ingress AUDIT R12's follow-up did not enumerate: its hash fields are `Vec<u8>`
/// and `casper::event_converter`'s `bytes_to_hash` hands them to `Blake2b256Hash::from_byte_array`,
/// which asserts the length. A peer's `BlockMessage` carrying a short event hash therefore panicked
/// during replay, on the same 32 MiB worker the block path runs on. The check belongs here, at the
/// only place peer bytes enter an `Event`; the fields stay `Vec<u8>` (re-typing them would ripple
/// into the `Vec<u8>`-valued helpers in `casper/src/api/block_api_impl.rs`, so it is recorded as a
/// boundary rather than done here).
fn wire_hash(bytes: &[u8]) -> Result<Vec<u8>, crate::errors::ModelsError> {
    Blake2b256Hash::try_from(bytes)
        .map(|_| bytes.to_vec())
        .map_err(|_| crate::errors::ModelsError::Malformed("event hash is not 32 bytes"))
}

/// Collect a list of wire hashes, refusing the whole list on the first wrong length.
fn wire_hashes(hashes: &[Vec<u8>]) -> Result<Vec<Vec<u8>>, crate::errors::ModelsError> {
    hashes.iter().map(|h| wire_hash(h)).collect()
}

impl Event {
    pub fn from_proto(e: &EventProto) -> Result<Event, crate::errors::ModelsError> {
        match &e.event_instance {
            Some(event_proto::EventInstance::Produce(pe)) => Ok(Event::Produce(ProduceEvent {
                channels_hash: wire_hash(&pe.channels_hash)?,
                hash: wire_hash(&pe.hash)?,
                persistent: pe.persistent,
                times_repeated: pe.times_repeated,
            })),
            Some(event_proto::EventInstance::Consume(ce)) => Ok(Event::Consume(ConsumeEvent {
                channels_hashes: wire_hashes(&ce.channels_hashes)?,
                hash: wire_hash(&ce.hash)?,
                persistent: ce.persistent,
            })),
            Some(event_proto::EventInstance::Comm(ce)) => {
                let consume = ce
                    .consume
                    .as_ref()
                    .ok_or(crate::errors::ModelsError::Malformed(
                        "malformed CommEvent: missing consume",
                    ))?;
                Ok(Event::Comm(CommEvent {
                    consume: ConsumeEvent {
                        channels_hashes: wire_hashes(&consume.channels_hashes)?,
                        hash: wire_hash(&consume.hash)?,
                        persistent: consume.persistent,
                    },
                    produces: ce
                        .produces
                        .iter()
                        .map(|p| {
                            Ok(ProduceEvent {
                                channels_hash: wire_hash(&p.channels_hash)?,
                                hash: wire_hash(&p.hash)?,
                                persistent: p.persistent,
                                times_repeated: p.times_repeated,
                            })
                        })
                        .collect::<Result<Vec<_>, crate::errors::ModelsError>>()?,
                    peeks: ce
                        .peeks
                        .iter()
                        .map(|p| Peek {
                            channel_index: p.channel_index,
                        })
                        .collect(),
                }))
            }
            None => Err(crate::errors::ModelsError::Malformed(
                "malformed Event: empty",
            )),
        }
    }

    pub fn to_proto(&self) -> EventProto {
        match self {
            Event::Produce(pe) => EventProto {
                event_instance: Some(event_proto::EventInstance::Produce(ProduceEventProto {
                    channels_hash: pe.channels_hash.clone(),
                    hash: pe.hash.clone(),
                    persistent: pe.persistent,
                    times_repeated: pe.times_repeated,
                })),
            },
            Event::Consume(ce) => EventProto {
                event_instance: Some(event_proto::EventInstance::Consume(ConsumeEventProto {
                    channels_hashes: ce.channels_hashes.clone(),
                    hash: ce.hash.clone(),
                    persistent: ce.persistent,
                })),
            },
            Event::Comm(ce) => EventProto {
                event_instance: Some(event_proto::EventInstance::Comm(CommEventProto {
                    consume: Some(ConsumeEventProto {
                        channels_hashes: ce.consume.channels_hashes.clone(),
                        hash: ce.consume.hash.clone(),
                        persistent: ce.consume.persistent,
                    }),
                    produces: ce
                        .produces
                        .iter()
                        .map(|p| ProduceEventProto {
                            channels_hash: p.channels_hash.clone(),
                            hash: p.hash.clone(),
                            persistent: p.persistent,
                            times_repeated: p.times_repeated,
                        })
                        .collect(),
                    peeks: ce
                        .peeks
                        .iter()
                        .map(|p| PeekProto {
                            channel_index: p.channel_index,
                        })
                        .collect(),
                })),
            },
        }
    }
}

// -------------------------------------------------------------------------------------------------
// System deploys
// -------------------------------------------------------------------------------------------------

/// System deploy data (port of the sealed `SystemDeployData`).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SystemDeployData {
    /// A slash, and **what it takes** (AUDIT C199): the victim, and the tier its offence earns.
    ///
    /// The tier travels in the state because a replayer reconstructs this deploy from here and has no
    /// DAG to re-derive a tier from, and because a receiving node must be able to check it against its
    /// own derivation rather than trust the proposer's arithmetic. Code `0` is a slash recorded before
    /// the tiers existed, and it takes everything — which is what it did.
    Slash {
        validator: Validator,
        severity: SlashSeverity,
        /// **Equivocation evidence** (AUDIT C200): the offender's *second* block at a `(sender,
        /// seq_num)` the DAG already holds a **different** block for, as an
        /// [`EquivocationEvidence`] header.
        ///
        /// It travels because the H-1 gate refuses such a block *before any write*, so no node stores
        /// it and a receiver cannot look it up. The receiver does not need to have seen it, though: the
        /// offender's *first* block is in **its own DAG**, and the rest of the proof is a signature
        /// verification over content the evidence carries itself.
        ///
        /// **Serialized**, not a decoded header, for two reasons: this enum is `serde`, which the
        /// header's field types are not all of, and a block that contains a slash that contains a block
        /// would be a recursive type. The verifier decodes it when it checks it.
        ///
        /// `None` (empty on the wire) means the slash is justified the other way — by the offender's
        /// failed block sitting in the slashing block's justifications.
        evidence: Option<Vec<u8>>,
    },
    CloseBlock,
    /// **The cost-accounting deploys record as this** — a pre-charge, a refund and the producer's
    /// payment carry no block-level payload of their own — and a block written before the `RecordSpoke`
    /// variant was retired (B4, #150, 2026-10-02) reads as this too, because its proto field 3 is now
    /// *reserved* and prost decodes an unknown oneof field to `None`.
    ///
    /// **Those two are distinguished at replay, not here**: `replay_block_system_deploy` refuses an
    /// `Empty` entry in a block's system-deploy list, and the cost-accounting deploys reach replay by a
    /// different route. So an old block is rejected rather than silently no-oped — the right outcome
    /// from the wrong place, which is worth knowing before reading this arm as "nothing to do".
    Empty,
}

/// **The minimal proof of an equivocation** (AUDIT C200) — the offender's second block, reduced to the
/// header fields that make the offence checkable by a node that never saw it.
///
/// `models` owns the type because the wire form is a proto this module generates, and the *crypto* is
/// here too because this crate already depends on `rchain-crypto` ([`is_signed_by`] is one signature
/// verification, the same call `validate::block_signature` makes).
///
/// **Why the header and not the block.** This travels in a slashing block's own `state`, i.e. in
/// consensus data every node stores and every replayer reads — and a block the H-1 gate refused passed
/// no check at all, so its size is whatever the peer that produced it chose. Carrying the block would
/// therefore be an unbounded write into consensus state; every field here is fixed-width, so the
/// payload is a few hundred bytes no matter what the offender sends.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EquivocationEvidence {
    pub block_hash: BlockHash,
    pub sender: Validator,
    pub seq_num: SeqNum,
    pub sig: Vec<u8>,
    pub sig_algorithm: String,
}

impl EquivocationEvidence {
    /// The header of a block the gate refused.
    ///
    /// Read off the *block*, not off the metadata the gate matched on: the signature covers the block's
    /// own hash and sender, so the evidence has to be the block's own account of itself for
    /// [`is_signed_by`] to mean anything.
    pub fn from_block(block: &BlockMessage) -> Self {
        Self {
            block_hash: block.block_hash,
            sender: block.sender,
            seq_num: block.seq_num,
            sig: block.sig.clone(),
            sig_algorithm: block.sig_algorithm.clone(),
        }
    }

    /// The wire form — what a `Slash`'s `evidence` field carries.
    ///
    /// **The bytes are carried, not recomputed.** They are part of the block's state, so what matters is
    /// that they are the *same bytes* on play and replay, which they are because the replay reads them
    /// rather than re-encoding.
    pub fn encode(&self) -> Vec<u8> {
        let proto = EquivocationEvidenceProto {
            block_hash: self.block_hash.as_bytes().to_vec(),
            sender: self.sender.as_bytes().to_vec(),
            seq_num: i64::from(self.seq_num),
            sig: self.sig.clone(),
            sig_algorithm: self.sig_algorithm.clone(),
        };
        proto.encode_to_vec()
    }

    /// Parse the wire form, **validating every field on ingress**: a hash that is not 32 bytes and a
    /// sender that is not a key are refused here rather than reaching a slice or an assert.
    pub fn decode(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = EquivocationEvidenceProto::decode(bytes).map_err(|e| {
            crate::errors::ModelsError::Decode(format!("equivocation evidence: {e}"))
        })?;
        Ok(Self {
            block_hash: BlockHash::try_from(proto.block_hash.as_slice())?,
            sender: Validator::try_from(proto.sender.as_slice())?,
            seq_num: SeqNum::try_from(proto.seq_num)
                .map_err(|_| crate::errors::ModelsError::Malformed("negative sequence number"))?,
            sig: proto.sig,
            sig_algorithm: proto.sig_algorithm,
        })
    }

    /// **Does the named offender's own signature cover `block_hash`?**
    ///
    /// Both halves matter and neither is redundant: the sender check is what stops a proposer naming a
    /// victim and attaching its *own* signature, and the verification is what stops it inventing a
    /// hash the victim never signed. What is left is the offence itself — only the offender can produce
    /// this payload, and it can only produce it by signing once per sequence number.
    pub fn is_signed_by(&self, offender: &Validator) -> bool {
        if self.sender != *offender {
            return false;
        }
        match rchain_crypto::signatures::signatures_alg::from_algorithm(&self.sig_algorithm) {
            Some(alg) => alg.verify(
                self.block_hash.as_bytes(),
                &self.sig,
                self.sender.as_bytes(),
            ),
            None => false,
        }
    }
}

impl SystemDeployData {
    pub fn from_proto(p: &SystemDeployDataProto) -> Result<Self, crate::errors::ModelsError> {
        match &p.system_deploy {
            Some(system_deploy_data_proto::SystemDeploy::SlashSystemDeploy(sd)) => {
                let evidence = if sd.equivocation_evidence.is_empty() {
                    None
                } else {
                    Some(sd.equivocation_evidence.clone())
                };
                Ok(SystemDeployData::Slash {
                    validator: Validator::try_from(sd.slashed_validator.as_slice())?,
                    severity: SlashSeverity::from_code(sd.slash_severity),
                    evidence,
                })
            }
            Some(system_deploy_data_proto::SystemDeploy::CloseBlockSystemDeploy(_)) => {
                Ok(SystemDeployData::CloseBlock)
            }
            // An unknown oneof field in the schema as sent reads as `None` here, and `Empty` is what
            // that means — a block from before `RecordSpoke` was retired lands in this arm, and
            // `replay_block_system_deploy` is what refuses it. See the variant's own doc.
            None => Ok(SystemDeployData::Empty),
        }
    }

    pub fn to_proto(&self) -> SystemDeployDataProto {
        match self {
            SystemDeployData::Slash {
                validator,
                severity,
                evidence,
            } => SystemDeployDataProto {
                system_deploy: Some(system_deploy_data_proto::SystemDeploy::SlashSystemDeploy(
                    SlashSystemDeployDataProto {
                        slashed_validator: validator.as_bytes().to_vec(),
                        slash_severity: severity.to_code(),
                        equivocation_evidence: evidence.clone().unwrap_or_default(),
                    },
                )),
            },
            SystemDeployData::CloseBlock => SystemDeployDataProto {
                system_deploy: Some(
                    system_deploy_data_proto::SystemDeploy::CloseBlockSystemDeploy(
                        CloseBlockSystemDeployDataProto {},
                    ),
                ),
            },
            SystemDeployData::Empty => SystemDeployDataProto {
                system_deploy: None,
            },
        }
    }
}

/// A processed system deploy (port of the sealed `ProcessedSystemDeploy`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProcessedSystemDeploy {
    Succeeded {
        event_list: Vec<Event>,
        system_deploy: SystemDeployData,
    },
    Failed {
        event_list: Vec<Event>,
        error_msg: String,
    },
}

impl ProcessedSystemDeploy {
    pub fn from_proto(p: &ProcessedSystemDeployProto) -> Result<Self, crate::errors::ModelsError> {
        let deploy_log: Result<Vec<Event>, crate::errors::ModelsError> =
            p.deploy_log.iter().map(Event::from_proto).collect();
        let deploy_log = deploy_log?;
        if p.error_msg.is_empty() {
            let system_deploy = match p.system_deploy.as_ref() {
                Some(sd) => SystemDeployData::from_proto(sd)?,
                None => SystemDeployData::Empty,
            };
            Ok(ProcessedSystemDeploy::Succeeded {
                event_list: deploy_log,
                system_deploy,
            })
        } else {
            Ok(ProcessedSystemDeploy::Failed {
                event_list: deploy_log,
                error_msg: p.error_msg.clone(),
            })
        }
    }

    pub fn to_proto(&self) -> ProcessedSystemDeployProto {
        match self {
            ProcessedSystemDeploy::Succeeded {
                event_list,
                system_deploy,
            } => ProcessedSystemDeployProto {
                system_deploy: Some(system_deploy.to_proto()),
                deploy_log: event_list.iter().map(Event::to_proto).collect(),
                error_msg: String::new(),
            },
            ProcessedSystemDeploy::Failed {
                event_list,
                error_msg,
            } => ProcessedSystemDeployProto {
                system_deploy: None,
                deploy_log: event_list.iter().map(Event::to_proto).collect(),
                error_msg: error_msg.clone(),
            },
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Rholang state
// -------------------------------------------------------------------------------------------------

/// A processed deploy (port of `ProcessedDeploy`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProcessedDeploy {
    pub deploy: SignedDeployData,
    pub cost: PCost,
    pub deploy_log: Vec<Event>,
    pub is_failed: bool,
    pub system_deploy_error: Option<String>,
}

impl ProcessedDeploy {
    pub fn from_proto(p: &ProcessedDeployProto) -> Result<Self, crate::errors::ModelsError> {
        let deploy = p
            .deploy
            .as_ref()
            .ok_or(crate::errors::ModelsError::Malformed(
                "malformed ProcessedDeploy: missing deploy",
            ))?;
        let deploy_log: Result<Vec<Event>, crate::errors::ModelsError> =
            p.deploy_log.iter().map(Event::from_proto).collect();
        Ok(ProcessedDeploy {
            deploy: SignedDeployData::from_proto(deploy),
            cost: p.cost.as_ref().map(PCost::from_proto).unwrap_or_default(),
            deploy_log: deploy_log?,
            is_failed: p.errored,
            system_deploy_error: if p.system_deploy_error.is_empty() {
                None
            } else {
                Some(p.system_deploy_error.clone())
            },
        })
    }

    pub fn to_proto(&self) -> ProcessedDeployProto {
        ProcessedDeployProto {
            deploy: Some(self.deploy.to_proto()),
            cost: Some(self.cost.to_proto()),
            deploy_log: self.deploy_log.iter().map(Event::to_proto).collect(),
            errored: self.is_failed,
            system_deploy_error: self.system_deploy_error.clone().unwrap_or_default(),
        }
    }

    /// Build the client-facing deploy info (port of `toDeployInfo`).
    pub fn to_deploy_info(&self) -> DeployInfo {
        DeployInfo {
            deployer: base16::encode(&self.deploy.deployer),
            term: self.deploy.data.term.clone(),
            timestamp: self.deploy.data.timestamp,
            sig: base16::encode(&self.deploy.sig),
            sig_algorithm: self.deploy.sig_algorithm.clone(),
            phlo_price: self.deploy.data.phlo_price,
            phlo_limit: self.deploy.data.phlo_limit,
            valid_after_block_number: self.deploy.data.valid_after_block_number,
            cost: self.cost.cost,
            errored: self.is_failed,
            system_deploy_error: self.system_deploy_error.clone().unwrap_or_default(),
        }
    }

    /// The phlo refunded after this deploy: `max(0, phlo_limit − cost) × phlo_price` (port of
    /// `ProcessedDeploy.refundAmount`). Computed in `i128` and clamped to `i64::MAX` so the refund
    /// cannot wrap. Shared by play and replay so the two paths cannot drift (S3).
    ///
    /// **The clamp is at both ends, and `NonNegI64` is why that matters** (AUDIT C109). The doc here
    /// used to say the result was "non-negative by construction", and that was true only while every
    /// input was: `remaining` is clamped to `>= 0` above, but `phlo_price` is a bare `i64` from the
    /// wire, so a negative price made the product negative, `i64::try_from` accepted it, and the
    /// function returned a negative refund — precisely the value `native.refund` guards against. The
    /// guard is the backstop; the type is the fix. Clamping the product at zero as well means the
    /// returned value is non-negative for *every* input, which is what the sentence now claims.
    pub fn refund_amount(&self) -> NonNegI64 {
        let remaining = self
            .deploy
            .data
            .phlo_limit
            .saturating_sub_unsigned(self.cost.cost)
            .max(0) as i128;
        let product = remaining * (self.deploy.data.phlo_price as i128);
        let clamped = i64::try_from(product).unwrap_or(i64::MAX);
        NonNegI64::saturating(clamped)
    }

    /// **The REV this deploy burned**: `cost × phlo_price` — the phlo it consumed, priced. This is
    /// what the staking vault keeps for the deploy once the refund has left, and it is the base the
    /// producer's share is taken from (B2, #150).
    ///
    /// The same shared-by-play-and-replay argument as [`Self::refund_amount`], whose bracketing this
    /// mirrors exactly — `cost` is a `u64` and `phlo_price` a bare `i64` off the wire, so the product
    /// is taken in `i128` and clamped at both ends. It is `charge − refund` whenever neither of those
    /// clamps, which is every deploy that plays normally; where they can disagree the vault's own
    /// arithmetic is authoritative and this is what the *share* is computed from, with the payment
    /// bounded by the share rather than by this value.
    pub fn burned_amount(&self) -> NonNegI64 {
        let product = i128::from(self.cost.cost) * i128::from(self.deploy.data.phlo_price);
        let clamped = i64::try_from(product).unwrap_or(i64::MAX);
        NonNegI64::saturating(clamped)
    }
}

/// Rholang tuple-space state change (port of `RholangState`).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RholangState {
    pub deploys: Vec<ProcessedDeploy>,
    pub system_deploys: Vec<ProcessedSystemDeploy>,
}

impl RholangState {
    pub fn from_proto(p: &RholangStateProto) -> Result<Self, crate::errors::ModelsError> {
        let deploys: Result<Vec<ProcessedDeploy>, crate::errors::ModelsError> =
            p.deploys.iter().map(ProcessedDeploy::from_proto).collect();
        let system_deploys: Result<Vec<ProcessedSystemDeploy>, crate::errors::ModelsError> = p
            .system_deploys
            .iter()
            .map(ProcessedSystemDeploy::from_proto)
            .collect();
        Ok(RholangState {
            deploys: deploys?,
            system_deploys: system_deploys?,
        })
    }

    pub fn to_proto(&self) -> RholangStateProto {
        RholangStateProto {
            deploys: self.deploys.iter().map(ProcessedDeploy::to_proto).collect(),
            system_deploys: self
                .system_deploys
                .iter()
                .map(ProcessedSystemDeploy::to_proto)
                .collect(),
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Block message
// -------------------------------------------------------------------------------------------------

/// A block message (port of `BlockMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockMessage {
    pub version: i32,
    pub shard_id: String,
    pub block_hash: BlockHash,
    pub block_number: BlockHeight,
    pub sender: Validator,
    pub seq_num: SeqNum,
    pub pre_state_hash: StateHash,
    pub post_state_hash: StateHash,
    pub justifications: Vec<BlockHash>,
    pub bonds: BTreeMap<Validator, NonNegI64>,
    pub rejected_deploys: std::collections::BTreeSet<Vec<u8>>,
    pub rejected_blocks: std::collections::BTreeSet<BlockHash>,
    pub rejected_senders: std::collections::BTreeSet<Vec<u8>>,
    pub state: RholangState,
    pub sig_algorithm: String,
    pub sig: Vec<u8>,
    /// Proposer's wall clock (ms since the Unix epoch) at block creation. Informational only: it is
    /// not a consensus input (validators ignore it); applications read it via `rho:block:data`.
    pub timestamp: i64,
}

impl BlockMessage {
    pub fn from_proto(bm: &BlockMessageProto) -> Result<BlockMessage, crate::errors::ModelsError> {
        let state = bm
            .state
            .as_ref()
            .ok_or(crate::errors::ModelsError::Malformed(
                "malformed BlockMessage: missing state",
            ))?;
        Ok(BlockMessage {
            version: bm.version,
            shard_id: bm.shard_id.clone(),
            block_hash: BlockHash::try_from(bm.block_hash.as_slice())?,
            block_number: BlockHeight::try_from(bm.block_number)
                .map_err(|_| crate::errors::ModelsError::Malformed("negative block number"))?,
            sender: Validator::try_from(bm.sender.as_slice())?,
            seq_num: SeqNum::try_from(bm.seq_num)
                .map_err(|_| crate::errors::ModelsError::Malformed("negative sequence number"))?,
            pre_state_hash: StateHash::try_from(bm.pre_state_hash.as_slice())?,
            post_state_hash: StateHash::try_from(bm.post_state_hash.as_slice())?,
            justifications: bm
                .justifications
                .iter()
                .map(|b| BlockHash::try_from(b.as_slice()))
                .collect::<Result<Vec<BlockHash>, crate::errors::ModelsError>>()?,
            bonds: bm
                .bonds
                .iter()
                .map(|b| {
                    let stake = NonNegI64::try_from(b.stake)
                        .map_err(|_| crate::errors::ModelsError::Malformed("negative bond stake"))?;
                    Ok((Validator::try_from(b.validator.as_slice())?, stake))
                })
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            rejected_deploys: bm.rejected_deploys.iter().cloned().collect(),
            rejected_blocks: bm
                .rejected_blocks
                .iter()
                .map(|b| BlockHash::try_from(b.as_slice()))
                .collect::<Result<std::collections::BTreeSet<BlockHash>, crate::errors::ModelsError>>()?,
            rejected_senders: bm.rejected_senders.iter().cloned().collect(),
            state: RholangState::from_proto(state)?,
            sig_algorithm: bm.sig_algorithm.clone(),
            sig: bm.sig.clone(),
            timestamp: bm.timestamp,
        })
    }

    /// Serialize with sorted justifications/bonds/rejections (Law 16 determinism).
    pub fn to_proto(&self) -> BlockMessageProto {
        let mut justifications: Vec<BlockHash> = self.justifications.clone();
        justifications.sort();
        let mut bonds: Vec<BondProto> = self
            .bonds
            .iter()
            .map(|(validator, stake)| BondProto {
                validator: validator.as_bytes().to_vec(),
                stake: i64::from(*stake),
            })
            .collect();
        bonds.sort_by(|a, b| a.validator.cmp(&b.validator));
        let mut rejected_deploys: Vec<Vec<u8>> = self.rejected_deploys.iter().cloned().collect();
        rejected_deploys.sort();
        let mut rejected_blocks: Vec<BlockHash> = self.rejected_blocks.iter().copied().collect();
        rejected_blocks.sort();
        let mut rejected_senders: Vec<Vec<u8>> = self.rejected_senders.iter().cloned().collect();
        rejected_senders.sort();

        BlockMessageProto {
            version: self.version,
            shard_id: self.shard_id.clone(),
            block_hash: self.block_hash.as_bytes().to_vec(),
            block_number: i64::from(self.block_number),
            sender: self.sender.as_bytes().to_vec(),
            seq_num: i64::from(self.seq_num),
            pre_state_hash: self.pre_state_hash.as_bytes().to_vec(),
            post_state_hash: self.post_state_hash.as_bytes().to_vec(),
            justifications: justifications
                .into_iter()
                .map(|b| b.as_bytes().to_vec())
                .collect(),
            bonds,
            rejected_deploys,
            rejected_blocks: rejected_blocks
                .into_iter()
                .map(|b| b.as_bytes().to_vec())
                .collect(),
            rejected_senders,
            state: Some(self.state.to_proto()),
            sig_algorithm: self.sig_algorithm.clone(),
            sig: self.sig.clone(),
            timestamp: self.timestamp,
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }

    /// **The wire form with the two self-referential fields cleared** — `block_hash` and `sig` — which
    /// is exactly what the content-addressed hash is taken over (`hashBlock`).
    ///
    /// A method here rather than a clone-then-clear at the caller, which is what `proto_util::hash_block`
    /// used to do: the clone deep-copies the whole block, and a block holds up to 255 deploys each with
    /// its term and event log, while the proto construction below copies all of that *again* — so the
    /// clone was pure surplus, paid on every block a node creates and every block it validates (issue
    /// #144's family A, candidate 4). The two fields are cleared on the **proto**, after it is built, so
    /// the bytes are the same bytes: the clearing is a field assignment either way, and `to_proto` reads
    /// neither field into any other.
    pub fn to_bytes_cleared(&self) -> Vec<u8> {
        let mut proto = self.to_proto();
        proto.block_hash = BlockHash::new([0u8; crate::block_hash::LENGTH])
            .as_bytes()
            .to_vec();
        proto.sig = Vec::new();
        proto.encode_to_vec()
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<BlockMessage, crate::errors::ModelsError> {
        let proto = BlockMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockMessage::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Approved block + tips + request messages
// -------------------------------------------------------------------------------------------------

/// **The fringe state of one block, carried on the wire for a restoring node** (AUDIT C188, #139).
///
/// `fringe` and `fringe_state_hash` are not block fields and are not covered by the block hash: they
/// are the *node's own* derivation, produced when it validates or creates the block. A node that
/// LFS-syncs a mature chain never validates what it restores, so without these it has no fringe to
/// replay from — and every block whose `close_block` anchors the epoch seed to the fringe state then
/// replays to a different post-state. Measured, 2 of 2 devnet attempts: the joiner stops at the
/// height it synced to.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockFringe {
    pub block_hash: BlockHash,
    pub fringe: BTreeSet<BlockHash>,
    pub fringe_state_hash: StateHash,
}

impl BlockFringe {
    pub fn from_proto(
        f: &crate::proto::casper::BlockFringeProto,
    ) -> Result<Self, crate::errors::ModelsError> {
        Ok(BlockFringe {
            block_hash: BlockHash::try_from(f.block_hash.as_slice())?,
            fringe: f
                .fringe
                .iter()
                .map(|h| BlockHash::try_from(h.as_slice()))
                .collect::<Result<BTreeSet<BlockHash>, crate::errors::ModelsError>>()?,
            fringe_state_hash: StateHash::try_from(f.fringe_state_hash.as_slice())?,
        })
    }

    pub fn to_proto(&self) -> crate::proto::casper::BlockFringeProto {
        crate::proto::casper::BlockFringeProto {
            block_hash: self.block_hash.as_bytes().to_vec(),
            fringe: self.fringe.iter().map(|h| h.as_bytes().to_vec()).collect(),
            fringe_state_hash: self.fringe_state_hash.as_bytes().to_vec(),
        }
    }
}

/// A finalized fringe (port of `FinalizedFringe`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FinalizedFringe {
    pub hashes: Vec<BlockHash>,
    pub state_hash: StateHash,
    /// The fringe state of each block in this fringe's ancestry, when the requester asked for it
    /// (#139). Empty means "not sent": either the requester did not ask, or the responder does not
    /// know the field — both of which are the pre-#139 behaviour rather than an error.
    pub ancestry: Vec<BlockFringe>,
}

impl FinalizedFringe {
    pub fn from_proto(f: &FinalizedFringeProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(FinalizedFringe {
            hashes: f
                .hashes
                .iter()
                .map(|h| BlockHash::try_from(h.as_slice()))
                .collect::<Result<Vec<BlockHash>, crate::errors::ModelsError>>()?,
            state_hash: StateHash::try_from(f.state_hash.as_slice())?,
            ancestry: f
                .ancestry
                .iter()
                .map(BlockFringe::from_proto)
                .collect::<Result<Vec<BlockFringe>, crate::errors::ModelsError>>()?,
        })
    }
    pub fn to_proto(&self) -> FinalizedFringeProto {
        FinalizedFringeProto {
            hashes: self.hashes.iter().map(|h| h.as_bytes().to_vec()).collect(),
            state_hash: self.state_hash.as_bytes().to_vec(),
            ancestry: self.ancestry.iter().map(BlockFringe::to_proto).collect(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = FinalizedFringeProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        FinalizedFringe::from_proto(&proto)
    }
}

/// A finalized-fringe request (port of `FinalizedFringeRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FinalizedFringeRequest {
    pub identifier: String,
    pub trim_state: bool,
    /// Ask the responder to fill the fringe's `ancestry` with the per-block fringe state a restoring
    /// node cannot derive for itself (#139). A responder that does not know the field ignores it, so
    /// a mixed pair degrades to the pre-#139 behaviour rather than failing.
    pub include_fringe_metadata: bool,
    /// **The block the requester named as the sync's root** (C259). `None` is an ordinary fringe
    /// request. `Some` asks the responder to build the fringe — and its `ancestry` — from *that*
    /// block rather than from its own latest fringe, which is what a recovery sync needs: a peer with
    /// finality frozen has no fringe to offer, and the answer to an ordinary request in that state is
    /// the genesis block, so a joining node would sync to block 0 and reject everything after it.
    ///
    /// The field is a bounded addition in the #139 shape: a responder that does not know it decodes
    /// the request as an ordinary one and answers with its latest fringe (or genesis on a frozen
    /// net), which is the pre-C259 behaviour rather than a failed sync.
    pub anchor: Option<BlockHash>,
}

/// A fork-choice tip request (port of `ForkChoiceTipRequest`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ForkChoiceTipRequest;

/// A has-block request (port of `HasBlockRequest`).
///
/// The hash is the 32-byte [`BlockHash`] refinement, not a `Vec<u8>`: these three variants used to
/// carry raw bytes, and the handler's first statement (`BlockHash::from_slice`) panicked on a short
/// one, so any connected peer could kill a shard's node-launch task. AUDIT R12 converted seven
/// message types and missed these three (and `Event`); the refinement makes the panic
/// unconstructible rather than guarded.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HasBlockRequest {
    pub hash: BlockHash,
}

/// A has-block response (port of `HasBlock`). See [`HasBlockRequest`] on the hash's refinement.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HasBlock {
    pub hash: BlockHash,
}

/// A block request (port of `BlockRequest`). See [`HasBlockRequest`] on the hash's refinement.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockRequest {
    pub hash: BlockHash,
}

/// A request for the blocks at heights `[from, to]` (C259's catch-up — see `BlockRangeRequestProto`).
///
/// **Why a height range exists at all.** Every other block request in this protocol is keyed by hash,
/// so a node that has just restored at an anchor well below the tip can only learn the gap by walking
/// *downward* from a peer's tip through `justifications` — and since each new block justifies blocks
/// inside the gap, that walk pulls the whole gap in at once and the receiver's pending set saturates
/// (`MAX_PENDING_BLOCKS`) before the node has covered it. A height range lets the walk be ordered.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockRangeRequest {
    pub from: i64,
    pub to: i64,
}

/// The answer to a [`BlockRangeRequest`]: the heights asked for, and the hashes at them in
/// **topological order** — ascending height, every parent before its children — so a requester can
/// validate them in the order they are listed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockRange {
    pub from: i64,
    pub to: i64,
    pub hashes: Vec<BlockHash>,
    /// The responder's own frontier (its highest block height), so a requester can tell "the peer has
    /// nothing above my frontier" from "the peer has nothing *in this window*" — the difference between
    /// ending a catch-up and chasing a producing peer for ever. `0` means the responder did not say.
    pub tip: i64,
}

/// A block-hash message (port of `BlockHashMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlockHashMessage {
    pub block_hash: BlockHash,
    pub block_creator: Vec<u8>,
}

impl FinalizedFringeRequest {
    /// Fallible because `anchor` is a [`BlockHash`] refinement: a wire value that is not 32 bytes is
    /// refused here rather than silently read as "no anchor", which would turn a corrupt request into
    /// a different request instead of an error.
    pub fn from_proto(m: &FinalizedFringeRequestProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(FinalizedFringeRequest {
            identifier: m.identifier.clone(),
            trim_state: m.trim_state,
            include_fringe_metadata: m.include_fringe_metadata,
            anchor: if m.anchor.is_empty() {
                None
            } else {
                Some(BlockHash::try_from(m.anchor.as_slice())?)
            },
        })
    }
    pub fn to_proto(&self) -> FinalizedFringeRequestProto {
        FinalizedFringeRequestProto {
            identifier: self.identifier.clone(),
            trim_state: self.trim_state,
            include_fringe_metadata: self.include_fringe_metadata,
            anchor: self
                .anchor
                .map(|h| h.as_bytes().to_vec())
                .unwrap_or_default(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = FinalizedFringeRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        FinalizedFringeRequest::from_proto(&proto)
    }
}

impl ForkChoiceTipRequest {
    pub fn to_proto(&self) -> ForkChoiceTipRequestProto {
        ForkChoiceTipRequestProto {}
    }
    pub fn from_proto(_m: &ForkChoiceTipRequestProto) -> Self {
        ForkChoiceTipRequest
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = ForkChoiceTipRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Ok(ForkChoiceTipRequest::from_proto(&proto))
    }
}

impl HasBlockRequest {
    pub fn from_proto(m: &HasBlockRequestProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(HasBlockRequest {
            hash: BlockHash::try_from(m.hash.as_slice())?,
        })
    }
    pub fn to_proto(&self) -> HasBlockRequestProto {
        HasBlockRequestProto {
            hash: self.hash.as_bytes().to_vec(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = HasBlockRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        HasBlockRequest::from_proto(&proto)
    }
}

impl HasBlock {
    pub fn from_proto(m: &HasBlockProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(HasBlock {
            hash: BlockHash::try_from(m.hash.as_slice())?,
        })
    }
    pub fn to_proto(&self) -> HasBlockProto {
        HasBlockProto {
            hash: self.hash.as_bytes().to_vec(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = HasBlockProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        HasBlock::from_proto(&proto)
    }
}

impl BlockRangeRequest {
    pub fn from_proto(m: &BlockRangeRequestProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(BlockRangeRequest {
            from: m.from,
            to: m.to,
        })
    }
    pub fn to_proto(&self) -> BlockRangeRequestProto {
        BlockRangeRequestProto {
            from: self.from,
            to: self.to,
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockRangeRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockRangeRequest::from_proto(&proto)
    }
}

impl BlockRange {
    /// **Every hash is a refinement, not raw bytes.** `BlockHash::try_from` refuses a short slice, so a
    /// peer cannot make this decoder panic the way AUDIT R12's three raw-`Vec<u8>` variants could —
    /// a malformed element is an `Err`, and the whole answer is dropped.
    pub fn from_proto(m: &BlockRangeProto) -> Result<Self, crate::errors::ModelsError> {
        let mut hashes = Vec::with_capacity(m.hashes.len());
        for h in &m.hashes {
            hashes.push(BlockHash::try_from(h.as_slice())?);
        }
        Ok(BlockRange {
            from: m.from,
            to: m.to,
            hashes,
            tip: m.tip,
        })
    }
    pub fn to_proto(&self) -> BlockRangeProto {
        BlockRangeProto {
            from: self.from,
            to: self.to,
            hashes: self.hashes.iter().map(|h| h.as_bytes().to_vec()).collect(),
            tip: self.tip,
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockRangeProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockRange::from_proto(&proto)
    }
}

impl BlockRequest {
    pub fn from_proto(m: &BlockRequestProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(BlockRequest {
            hash: BlockHash::try_from(m.hash.as_slice())?,
        })
    }
    pub fn to_proto(&self) -> BlockRequestProto {
        BlockRequestProto {
            hash: self.hash.as_bytes().to_vec(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockRequest::from_proto(&proto)
    }
}

impl BlockHashMessage {
    pub fn from_proto(m: &BlockHashMessageProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(BlockHashMessage {
            block_hash: BlockHash::try_from(m.hash.as_slice())?,
            block_creator: m.block_creator.clone(),
        })
    }
    pub fn to_proto(&self) -> BlockHashMessageProto {
        BlockHashMessageProto {
            hash: self.block_hash.as_bytes().to_vec(),
            block_creator: self.block_creator.clone(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = BlockHashMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        BlockHashMessage::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Store items (last finalized state)
// -------------------------------------------------------------------------------------------------

/// The non-existent store-node index encoding (port of `StoreNodeKey.noneIndex`).
const STORE_NODE_KEY_NONE_INDEX: i32 = 0x100;

/// Decode a `(hash, index)` store-node key (port of `StoreNodeKey.from`).
fn store_node_key_from_proto(
    s: &StoreNodeKeyProto,
) -> Result<(Blake2b256Hash, Option<u8>), crate::errors::ModelsError> {
    let hash = Blake2b256Hash::try_from(s.hash.as_slice())?;
    let idx = if s.index == STORE_NODE_KEY_NONE_INDEX {
        None
    } else {
        // Validate-on-ingress: reject an out-of-range index rather than truncating via `as u8`.
        Some(u8::try_from(s.index).map_err(|_| {
            crate::errors::ModelsError::Malformed("store node key index out of range")
        })?)
    };
    Ok((hash, idx))
}

/// Encode a `(hash, index)` store-node key (port of `StoreNodeKey.toProto`).
fn store_node_key_to_proto(s: &(Blake2b256Hash, Option<u8>)) -> StoreNodeKeyProto {
    StoreNodeKeyProto {
        hash: s.0.as_bytes().to_vec(),
        index: s.1.map(|b| b as i32).unwrap_or(STORE_NODE_KEY_NONE_INDEX),
    }
}

/// A store-items request (port of `StoreItemsMessageRequest`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoreItemsMessageRequest {
    pub start_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub skip: i32,
    pub take: i32,
}

impl StoreItemsMessageRequest {
    pub fn from_proto(
        m: &StoreItemsMessageRequestProto,
    ) -> Result<Self, crate::errors::ModelsError> {
        Ok(StoreItemsMessageRequest {
            start_path: m
                .start_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            skip: m.skip,
            take: m.take,
        })
    }
    pub fn to_proto(&self) -> StoreItemsMessageRequestProto {
        StoreItemsMessageRequestProto {
            start_path: self
                .start_path
                .iter()
                .map(store_node_key_to_proto)
                .collect(),
            skip: self.skip,
            take: self.take,
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = StoreItemsMessageRequestProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Self::from_proto(&proto)
    }
}

/// A store-items response (port of `StoreItemsMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoreItemsMessage {
    pub start_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub last_path: Vec<(Blake2b256Hash, Option<u8>)>,
    pub history_items: Vec<(Blake2b256Hash, Vec<u8>)>,
    pub data_items: Vec<(Blake2b256Hash, Vec<u8>)>,
}

impl StoreItemsMessage {
    pub fn from_proto(m: &StoreItemsMessageProto) -> Result<Self, crate::errors::ModelsError> {
        Ok(StoreItemsMessage {
            start_path: m
                .start_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            last_path: m
                .last_path
                .iter()
                .map(store_node_key_from_proto)
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            history_items: m
                .history_items
                .iter()
                .map(|y| Ok((Blake2b256Hash::try_from(y.key.as_slice())?, y.value.clone())))
                .collect::<Result<_, crate::errors::ModelsError>>()?,
            data_items: m
                .data_items
                .iter()
                .map(|y| Ok((Blake2b256Hash::try_from(y.key.as_slice())?, y.value.clone())))
                .collect::<Result<_, crate::errors::ModelsError>>()?,
        })
    }
    pub fn to_proto(&self) -> StoreItemsMessageProto {
        StoreItemsMessageProto {
            start_path: self
                .start_path
                .iter()
                .map(store_node_key_to_proto)
                .collect(),
            last_path: self.last_path.iter().map(store_node_key_to_proto).collect(),
            history_items: self
                .history_items
                .iter()
                .map(|(k, v)| StoreItemProto {
                    key: k.as_bytes().to_vec(),
                    value: v.clone(),
                })
                .collect(),
            data_items: self
                .data_items
                .iter()
                .map(|(k, v)| StoreItemProto {
                    key: k.as_bytes().to_vec(),
                    value: v.clone(),
                })
                .collect(),
        }
    }
    pub fn to_bytes(&self) -> Vec<u8> {
        self.to_proto().encode_to_vec()
    }
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::errors::ModelsError> {
        let proto = StoreItemsMessageProto::decode(bytes)
            .map_err(|e| crate::errors::ModelsError::Decode(e.to_string()))?;
        Self::from_proto(&proto)
    }
}

// -------------------------------------------------------------------------------------------------
// Casper message (sum type)
// -------------------------------------------------------------------------------------------------

/// The sealed `CasperMessage` sum type (port of the Scala `sealed trait CasperMessage`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CasperMessage {
    BlockMessage(BlockMessage),
    BlockRequest(BlockRequest),
    BlockRangeRequest(BlockRangeRequest),
    BlockRange(BlockRange),
    BlockHashMessage(BlockHashMessage),
    HasBlock(HasBlock),
    HasBlockRequest(HasBlockRequest),
    ForkChoiceTipRequest(ForkChoiceTipRequest),
    FinalizedFringe(FinalizedFringe),
    FinalizedFringeRequest(FinalizedFringeRequest),
    StoreItemsMessageRequest(StoreItemsMessageRequest),
    StoreItemsMessage(StoreItemsMessage),
}

/// The sealed `CasperMessageProto` sum type (the scalapb `sealed trait CasperMessageProto`).
#[derive(Clone, Debug, PartialEq)]
pub enum CasperMessageProto {
    BlockMessage(BlockMessageProto),
    BlockRequest(BlockRequestProto),
    BlockRangeRequest(BlockRangeRequestProto),
    BlockRange(BlockRangeProto),
    BlockHashMessage(BlockHashMessageProto),
    HasBlock(HasBlockProto),
    HasBlockRequest(HasBlockRequestProto),
    ForkChoiceTipRequest(ForkChoiceTipRequestProto),
    FinalizedFringe(FinalizedFringeProto),
    FinalizedFringeRequest(FinalizedFringeRequestProto),
    StoreItemsMessageRequest(StoreItemsMessageRequestProto),
    StoreItemsMessage(StoreItemsMessageProto),
}

impl CasperMessage {
    pub fn from_proto(
        cm: &CasperMessageProto,
    ) -> Result<CasperMessage, crate::errors::ModelsError> {
        match cm {
            CasperMessageProto::BlockMessage(m) => {
                Ok(CasperMessage::BlockMessage(BlockMessage::from_proto(m)?))
            }
            CasperMessageProto::BlockRequest(m) => {
                Ok(CasperMessage::BlockRequest(BlockRequest::from_proto(m)?))
            }
            CasperMessageProto::BlockRangeRequest(m) => Ok(CasperMessage::BlockRangeRequest(
                BlockRangeRequest::from_proto(m)?,
            )),
            CasperMessageProto::BlockRange(m) => {
                Ok(CasperMessage::BlockRange(BlockRange::from_proto(m)?))
            }
            CasperMessageProto::BlockHashMessage(m) => Ok(CasperMessage::BlockHashMessage(
                BlockHashMessage::from_proto(m)?,
            )),
            CasperMessageProto::HasBlock(m) => {
                Ok(CasperMessage::HasBlock(HasBlock::from_proto(m)?))
            }
            CasperMessageProto::HasBlockRequest(m) => Ok(CasperMessage::HasBlockRequest(
                HasBlockRequest::from_proto(m)?,
            )),
            CasperMessageProto::ForkChoiceTipRequest(_) => {
                Ok(CasperMessage::ForkChoiceTipRequest(ForkChoiceTipRequest))
            }
            CasperMessageProto::FinalizedFringe(m) => Ok(CasperMessage::FinalizedFringe(
                FinalizedFringe::from_proto(m)?,
            )),
            CasperMessageProto::FinalizedFringeRequest(m) => Ok(
                CasperMessage::FinalizedFringeRequest(FinalizedFringeRequest::from_proto(m)?),
            ),
            CasperMessageProto::StoreItemsMessageRequest(m) => Ok(
                CasperMessage::StoreItemsMessageRequest(StoreItemsMessageRequest::from_proto(m)?),
            ),
            CasperMessageProto::StoreItemsMessage(m) => Ok(CasperMessage::StoreItemsMessage(
                StoreItemsMessage::from_proto(m)?,
            )),
        }
    }

    pub fn to_proto(&self) -> CasperMessageProto {
        match self {
            CasperMessage::BlockMessage(m) => CasperMessageProto::BlockMessage(m.to_proto()),
            CasperMessage::BlockRequest(m) => CasperMessageProto::BlockRequest(m.to_proto()),
            CasperMessage::BlockRangeRequest(m) => {
                CasperMessageProto::BlockRangeRequest(m.to_proto())
            }
            CasperMessage::BlockRange(m) => CasperMessageProto::BlockRange(m.to_proto()),
            CasperMessage::BlockHashMessage(m) => {
                CasperMessageProto::BlockHashMessage(BlockHashMessageProto {
                    hash: m.block_hash.as_bytes().to_vec(),
                    block_creator: m.block_creator.clone(),
                })
            }
            CasperMessage::HasBlock(m) => CasperMessageProto::HasBlock(m.to_proto()),
            CasperMessage::HasBlockRequest(m) => CasperMessageProto::HasBlockRequest(m.to_proto()),
            CasperMessage::ForkChoiceTipRequest(_) => {
                CasperMessageProto::ForkChoiceTipRequest(ForkChoiceTipRequestProto {})
            }
            CasperMessage::FinalizedFringe(m) => CasperMessageProto::FinalizedFringe(m.to_proto()),
            CasperMessage::FinalizedFringeRequest(m) => {
                CasperMessageProto::FinalizedFringeRequest(m.to_proto())
            }
            CasperMessage::StoreItemsMessageRequest(m) => {
                CasperMessageProto::StoreItemsMessageRequest(m.to_proto())
            }
            CasperMessage::StoreItemsMessage(m) => {
                CasperMessageProto::StoreItemsMessage(m.to_proto())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block_hash(byte: u8) -> BlockHash {
        BlockHash::new([byte; 32])
    }

    fn validator(byte: u8) -> Validator {
        Validator::new([byte; 65])
    }

    fn empty_block() -> BlockMessage {
        BlockMessage {
            version: 1,
            shard_id: "root".to_string(),
            block_hash: block_hash(0),
            block_number: 0.try_into().unwrap(),
            sender: validator(1),
            seq_num: 0.try_into().unwrap(),
            pre_state_hash: StateHash::new([0u8; 32]),
            post_state_hash: StateHash::new([0u8; 32]),
            justifications: Vec::new(),
            bonds: BTreeMap::new(),
            rejected_deploys: std::collections::BTreeSet::new(),
            rejected_blocks: std::collections::BTreeSet::new(),
            rejected_senders: std::collections::BTreeSet::new(),
            state: RholangState::default(),
            sig_algorithm: "secp256k1".to_string(),
            sig: Vec::new(),
            timestamp: 0,
        }
    }

    /// **`to_bytes_cleared` is the same bytes as the clone-then-clear it replaced** (issue #144's
    /// family A, candidate 4).
    ///
    /// The change is only sound if the two routes agree **byte for byte**: the block's hash is taken
    /// over exactly these bytes, so a field cleared differently would be a different hash, and a
    /// different hash is a chain split. The test builds a block that carries a deploy with a real term
    /// and event log — so the clone being removed was copying something — and requires the two
    /// encodings to be equal, with the uncleared encoding asserted different as the control that the
    /// clearing is doing work at all.
    #[test]
    fn the_cleared_encoding_matches_the_clone_then_clear_it_replaced() {
        let mut block = empty_block();
        block.state.deploys = vec![ProcessedDeploy {
            deploy: SignedDeployData {
                data: DeployData {
                    term: "x".repeat(4096),
                    timestamp: 0,
                    phlo_price: 1,
                    phlo_limit: 100,
                    valid_after_block_number: 0,
                    shard_id: "root".to_string(),
                    attachments: Vec::new(),
                },
                deployer: vec![1u8; 65],
                sig: vec![2u8; 64],
                sig_algorithm: "secp256k1".to_string(),
            },
            cost: PCost { cost: 1 },
            deploy_log: Vec::new(),
            is_failed: false,
            system_deploy_error: None,
        }];
        block.sig = vec![7u8; 64];
        block.block_hash = block_hash(9);

        let mut cleared = block.clone();
        cleared.block_hash = BlockHash::new([0u8; 32]);
        cleared.sig = Vec::new();

        assert_eq!(
            block.to_bytes_cleared(),
            cleared.to_bytes(),
            "the hash is taken over these bytes; a difference here is a different block"
        );
        assert_ne!(
            block.to_bytes(),
            block.to_bytes_cleared(),
            "the control: this block does carry a hash and a signature, so the clearing does work"
        );
    }

    /// **Every `CasperMessage` variant survives its own wire codec.** The tests here round-trip
    /// `BlockMessage` only, so `to_proto`/`from_proto`'s other eight arms — and the
    /// `to_bytes`/`from_bytes` pairs of the standalone request types — had never run. A variant that
    /// dropped a field on the way out, or decoded another variant's field, would compile, send, and
    /// arrive subtly wrong; each row is built, encoded, decoded and compared **whole**, so a dropped
    /// or transposed field fails here rather than surviving as a default. (The `body` corpus is the
    /// same idea one layer down for `BlockMessage`'s bytes; this is the message layer.)
    #[test]
    fn every_message_variant_round_trips_through_its_codec() {
        let cases: Vec<CasperMessage> = vec![
            CasperMessage::BlockRequest(BlockRequest {
                hash: block_hash(1),
            }),
            CasperMessage::BlockHashMessage(BlockHashMessage {
                block_hash: block_hash(7),
                block_creator: vec![9, 8, 7],
            }),
            CasperMessage::HasBlock(HasBlock {
                hash: block_hash(4),
            }),
            CasperMessage::HasBlockRequest(HasBlockRequest {
                hash: block_hash(6),
            }),
            CasperMessage::ForkChoiceTipRequest(ForkChoiceTipRequest),
            CasperMessage::FinalizedFringe(FinalizedFringe {
                hashes: vec![block_hash(1), block_hash(2)],
                state_hash: StateHash::new([3u8; 32]),
                ancestry: Vec::new(),
            }),
            CasperMessage::FinalizedFringeRequest(FinalizedFringeRequest {
                identifier: "peer-1".to_string(),
                trim_state: true,
                include_fringe_metadata: true,
                anchor: None,
            }),
            CasperMessage::StoreItemsMessageRequest(StoreItemsMessageRequest {
                start_path: vec![(Blake2b256Hash::from_bytes([4u8; 32]), Some(2))],
                skip: 3,
                take: 4,
            }),
            CasperMessage::StoreItemsMessage(StoreItemsMessage {
                start_path: vec![(Blake2b256Hash::from_bytes([5u8; 32]), None)],
                last_path: vec![(Blake2b256Hash::from_bytes([6u8; 32]), Some(1))],
                history_items: vec![(Blake2b256Hash::from_bytes([7u8; 32]), vec![1, 2])],
                data_items: vec![(Blake2b256Hash::from_bytes([8u8; 32]), vec![3, 4])],
            }),
        ];
        for case in cases {
            let proto = case.to_proto();
            let back = CasperMessage::from_proto(&proto)
                .unwrap_or_else(|e| panic!("{case:?} did not decode: {e:?}"));
            assert_eq!(back, case, "a variant round trips whole");
        }
    }

    /// A peer that sends a hash that is not 32 bytes must be **refused at decode**, not panicked on
    /// later. `BlockRequest`/`HasBlock`/`HasBlockRequest` carried `Vec<u8>` and were cloned
    /// unchecked, and the handler's first statement called `BlockHash::from_slice`, whose length
    /// assert unwinds. AUDIT R12 converted seven message types and missed these three.
    ///
    /// Each test below is the falsifier for that fix: it asserts `Err` where the tree returned `Ok`
    /// (and the panic followed in the handler).
    #[test]
    fn block_request_with_a_short_hash_is_refused() {
        let proto = CasperMessageProto::BlockRequest(BlockRequestProto {
            hash: vec![1, 2, 3],
        });
        assert!(
            CasperMessage::from_proto(&proto).is_err(),
            "BlockRequest accepted a 3-byte hash; the handler then panics in BlockHash::from_slice"
        );
    }

    #[test]
    fn has_block_with_a_short_hash_is_refused() {
        let proto = CasperMessageProto::HasBlock(HasBlockProto { hash: vec![4, 5] });
        assert!(
            CasperMessage::from_proto(&proto).is_err(),
            "HasBlock accepted a 2-byte hash; the handler then panics in BlockHash::from_slice"
        );
    }

    #[test]
    fn has_block_request_with_a_short_hash_is_refused() {
        let proto = CasperMessageProto::HasBlockRequest(HasBlockRequestProto { hash: vec![6] });
        assert!(
            CasperMessage::from_proto(&proto).is_err(),
            "HasBlockRequest accepted a 1-byte hash; the handler then panics in BlockHash::from_slice"
        );
    }

    /// The same refusal one layer down, at the raw-bytes entry a peer's packet content takes:
    /// `from_bytes` decodes the proto and then runs the checked `from_proto`. This is the closest
    /// test to the socket, and unlike a hand-built byte literal it cannot pass vacuously — the proto
    /// is constructed through the generated type, so the only thing that can make it fail is the
    /// length check under test.
    #[test]
    fn block_request_from_bytes_refuses_a_short_hash() {
        let bytes = BlockRequestProto {
            hash: vec![1, 2, 3],
        }
        .encode_to_vec();
        assert!(
            BlockRequest::from_bytes(&bytes).is_err(),
            "a 3-byte hash decoded from raw bytes; the handler then panics in BlockHash::from_slice"
        );
    }

    /// The fourth ingress R12's follow-up missed. A peer's `BlockMessage` carries this trace, and
    /// the replay path handed the bytes to `Blake2b256Hash::from_byte_array`, whose length assert
    /// unwinds — so the same three bytes that kill the shard through a `BlockRequest` also killed it
    /// through block replay.
    #[test]
    fn event_with_a_short_hash_is_refused() {
        let proto = EventProto {
            event_instance: Some(event_proto::EventInstance::Produce(ProduceEventProto {
                channels_hash: vec![1u8; 32],
                hash: vec![2, 3],
                persistent: false,
                times_repeated: 0,
            })),
        };
        assert!(
            Event::from_proto(&proto).is_err(),
            "a 2-byte event hash decoded; the replay path then panics in Blake2b256Hash::from_byte_array"
        );
    }

    #[test]
    fn block_message_round_trip_preserves_timestamp() {
        // The informational timestamp is carried in the header proto, so every node (and replay)
        // decodes the same value.
        let mut block = empty_block();
        block.timestamp = 1_700_000_000_000;
        let round = BlockMessage::from_bytes(&block.to_bytes()).expect("round trip");
        assert_eq!(round.timestamp, block.timestamp);
    }

    #[test]
    fn law16_to_proto_sorts_justifications() {
        let mut block = empty_block();
        block.justifications = vec![block_hash(3), block_hash(1), block_hash(2)];
        let proto = block.to_proto();
        assert_eq!(
            proto.justifications,
            vec![
                block_hash(1).as_bytes().to_vec(),
                block_hash(2).as_bytes().to_vec(),
                block_hash(3).as_bytes().to_vec(),
            ]
        );
    }

    /// **The wire order of `bonds`/`rejected_blocks` — and the boundary this test is on.** Its
    /// name claimed to witness `to_proto`'s sorts for these two fields; *measured*, it cannot: with
    /// both `bonds.sort_by` and `rejected_blocks.sort()` deleted, this test passes — and so do the
    /// other 155 tests in this crate, so nothing else catches them either. The reason is the types:
    /// both fields are collected from a `BTreeMap`/`BTreeSet`, whose iteration order is already the
    /// sorted order the assertion checks, so the sorts are redundant here and no input can make them
    /// observable. (The *justifications* sort is a real witness — `to_proto_sorts_justifications`
    /// builds an unsorted `Vec` — and it is a different field.)
    ///
    /// So this pins the wire order the block hash depends on, which is worth keeping; what it must
    /// not do is read as evidence for the sorts. The register's Law 16c row carries the boundary:
    /// `Canonical` (justifications sorted) is checked for the field that can be unsorted.
    #[test]
    fn to_proto_keeps_bonds_and_rejections_in_sorted_order() {
        let mut block = empty_block();
        block.bonds = BTreeMap::from([
            (validator(3), 1.try_into().unwrap()),
            (validator(1), 2.try_into().unwrap()),
            (validator(2), 3.try_into().unwrap()),
        ]);
        block.rejected_blocks = [block_hash(9), block_hash(1)].into_iter().collect();
        let proto = block.to_proto();
        // Bonds already iterated in key order (BTreeMap) and then sorted by validator bytes.
        let validators: Vec<u8> = proto.bonds.iter().map(|b| b.validator[0]).collect();
        assert_eq!(validators, vec![1, 2, 3]);
        assert_eq!(
            proto.rejected_blocks,
            vec![
                block_hash(1).as_bytes().to_vec(),
                block_hash(9).as_bytes().to_vec()
            ]
        );
    }

    #[test]
    fn block_message_round_trips() {
        let mut block = empty_block();
        block.justifications = vec![block_hash(1), block_hash(2)];
        block.bonds = BTreeMap::from([(validator(1), 100.try_into().unwrap())]);
        block.rejected_blocks = [block_hash(7)].into_iter().collect();
        let bytes = block.to_bytes();
        let decoded = BlockMessage::from_bytes(&bytes).unwrap();
        assert_eq!(decoded, block);
    }

    #[test]
    fn finalized_fringe_round_trips() {
        let fringe = FinalizedFringe {
            hashes: vec![block_hash(1), block_hash(2)],
            state_hash: StateHash::new([7u8; 32]),
            ancestry: Vec::new(),
        };
        let decoded = FinalizedFringe::from_bytes(&fringe.to_bytes()).unwrap();
        assert_eq!(decoded, fringe);
    }

    /// **The per-block fringe state survives the wire** (AUDIT C188, #139).
    ///
    /// A joining node cannot derive `fringe`/`fringe_state_hash` for the blocks it restores — they are
    /// the *proposer's* own recomputation and are not block fields — so this field is the whole of what
    /// makes a mature join replayable. A codec that dropped it would put every joiner back at the
    /// pre-#139 behaviour with no other symptom, which is why it is pinned as a round trip rather than
    /// left to the devnet to notice.
    ///
    /// The request flag is pinned with it: a responder reads *that* to decide whether to send the
    /// ancestry at all, so a codec that dropped the flag would silently turn the addition off.
    /// A height window round-trips through the wire, and **a hash that is not 32 bytes is refused by
    /// the decoder rather than panicking in the handler** — AUDIT R12's class: three message types
    /// carried raw `Vec<u8>` and the handler's first statement panicked on a short one, so any
    /// connected peer could kill a shard's task. The refinement makes that unconstructible.
    #[test]
    fn a_block_range_round_trips_and_a_short_hash_is_refused() {
        let h1 = BlockHash::new([1u8; 32]);
        let h2 = BlockHash::new([2u8; 32]);
        let range = BlockRange {
            from: 3,
            to: 4,
            hashes: vec![h1, h2],
            tip: 99,
        };
        let decoded = BlockRange::from_bytes(&range.to_bytes()).expect("round trip");
        assert_eq!(decoded, range);

        let req = BlockRangeRequest { from: 3, to: 4 };
        assert_eq!(
            BlockRangeRequest::from_bytes(&req.to_bytes()).expect("round trip"),
            req
        );

        let short = BlockRangeProto {
            from: 3,
            to: 4,
            hashes: vec![vec![7u8; 31]],
            tip: 99,
        };
        assert!(
            BlockRange::from_proto(&short).is_err(),
            "a 31-byte hash is an error, not a panic"
        );
    }

    #[test]
    fn the_fringe_ancestry_round_trips() {
        let fringe = FinalizedFringe {
            hashes: vec![block_hash(2)],
            state_hash: StateHash::new([7u8; 32]),
            ancestry: vec![
                BlockFringe {
                    block_hash: block_hash(1),
                    fringe: BTreeSet::new(),
                    fringe_state_hash: StateHash::new([9u8; 32]),
                },
                BlockFringe {
                    block_hash: block_hash(2),
                    fringe: [block_hash(1)].into_iter().collect(),
                    fringe_state_hash: StateHash::new([8u8; 32]),
                },
            ],
        };
        let decoded = FinalizedFringe::from_bytes(&fringe.to_bytes()).unwrap();
        assert_eq!(decoded, fringe, "the ancestry must survive the wire");

        let req = FinalizedFringeRequest {
            identifier: "joiner".to_string(),
            trim_state: false,
            include_fringe_metadata: true,
            anchor: Some(block_hash(5)),
        };
        let decoded = FinalizedFringeRequest::from_bytes(&req.to_bytes()).unwrap();
        assert_eq!(decoded, req, "and so must the flag that asks for it");
        assert_eq!(
            decoded.anchor,
            Some(block_hash(5)),
            "and the anchor the recovery sync names (C259)"
        );

        // A **request without an anchor** round-trips as one: the two states are distinct on the wire,
        // so an ordinary fringe request cannot be read as a recovery sync that named block 0.
        let plain = FinalizedFringeRequest {
            anchor: None,
            ..req.clone()
        };
        let decoded = FinalizedFringeRequest::from_bytes(&plain.to_bytes()).unwrap();
        assert_eq!(decoded.anchor, None, "no anchor is not the zero hash");

        // **An anchor that is not a block hash is refused, not read as an absent one.** `anchor` is a
        // refinement, and a 31-byte value is a corrupt request rather than an ordinary one — reading it
        // as `None` would silently answer a different question (C259's whole failure mode).
        let short = FinalizedFringeRequestProto {
            identifier: "old".to_string(),
            trim_state: false,
            anchor: vec![0u8; 31],
            ..Default::default()
        };
        assert!(
            FinalizedFringeRequest::from_proto(&short).is_err(),
            "a malformed anchor must not decode as an ordinary fringe request"
        );

        // The defaults are **off**: a requester that does not know either field sends `false`/empty,
        // and the responder then sends no ancestry and answers from its own latest fringe — which is
        // what makes these non-breaking additions rather than a change every node makes at once.
        let proto = FinalizedFringeRequestProto {
            identifier: "old".to_string(),
            trim_state: false,
            ..Default::default()
        };
        let old = FinalizedFringeRequest::from_proto(&proto).expect("an ordinary request");
        assert!(!old.include_fringe_metadata);
        assert_eq!(old.anchor, None);
    }

    #[test]
    fn casper_message_block_round_trips() {
        let msg = CasperMessage::BlockMessage(empty_block());
        let proto = msg.to_proto();
        let decoded = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded, msg);
    }

    #[test]
    fn store_items_message_round_trips() {
        let msg = StoreItemsMessage {
            start_path: vec![(Blake2b256Hash::from_bytes([1u8; 32]), None)],
            last_path: vec![(Blake2b256Hash::from_bytes([2u8; 32]), Some(3))],
            history_items: vec![(Blake2b256Hash::from_bytes([4u8; 32]), vec![5, 6])],
            data_items: vec![(Blake2b256Hash::from_bytes([7u8; 32]), vec![8])],
        };
        let decoded = StoreItemsMessage::from_bytes(&msg.to_bytes()).unwrap();
        assert_eq!(decoded, msg);

        let casper = CasperMessage::StoreItemsMessage(msg.clone());
        let proto = casper.to_proto();
        let decoded_casper = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded_casper, casper);
    }

    #[test]
    fn store_items_message_request_round_trips() {
        let req = StoreItemsMessageRequest {
            start_path: vec![(Blake2b256Hash::from_bytes([9u8; 32]), Some(1))],
            skip: 2,
            take: 3,
        };
        let decoded = StoreItemsMessageRequest::from_bytes(&req.to_bytes()).unwrap();
        assert_eq!(decoded, req);

        let casper = CasperMessage::StoreItemsMessageRequest(req.clone());
        let proto = casper.to_proto();
        let decoded_casper = CasperMessage::from_proto(&proto).unwrap();
        assert_eq!(decoded_casper, casper);
    }

    fn signed_deploy_data(term: &str) -> SignedDeployData {
        use rchain_crypto::signatures::secp256k1::Secp256k1;
        use rchain_crypto::signatures::signatures_alg::SignaturesAlg;
        use rchain_crypto::signatures::signed::Signed;
        let (sec, _pk) = Secp256k1.new_key_pair();
        let data = DeployData {
            attachments: Vec::new(),
            term: term.to_string(),
            timestamp: 0,
            phlo_price: 1,
            phlo_limit: 100,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
        };
        let signed = Signed::new(data, &Secp256k1, &sec).unwrap();
        SignedDeployData {
            data: signed.data,
            deployer: signed.pk.bytes().to_vec(),
            sig: signed.sig,
            sig_algorithm: signed.sig_algorithm.name().to_string(),
        }
    }

    #[test]
    fn verify_signature_accepts_valid_deploy() {
        assert!(signed_deploy_data("Nil").verify_signature());
    }

    #[test]
    fn verify_signature_rejects_tampered_term() {
        let mut sd = signed_deploy_data("Nil");
        sd.data.term = "Nil | Nil".to_string();
        assert!(!sd.verify_signature());
    }

    #[test]
    fn verify_signature_rejects_unknown_algorithm() {
        let mut sd = signed_deploy_data("Nil");
        sd.sig_algorithm = "bogus".to_string();
        assert!(!sd.verify_signature());
    }

    fn signed_deploy_with_attachments(attachments: Vec<Vec<u8>>) -> SignedDeployData {
        use rchain_crypto::signatures::secp256k1::Secp256k1;
        use rchain_crypto::signatures::signatures_alg::SignaturesAlg;
        use rchain_crypto::signatures::signed::Signed;
        let (sec, _pk) = Secp256k1.new_key_pair();
        let data = DeployData {
            term: "Nil".to_string(),
            timestamp: 0,
            phlo_price: 1,
            phlo_limit: 100,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
            attachments,
        };
        let signed = Signed::new(data, &Secp256k1, &sec).unwrap();
        SignedDeployData {
            data: signed.data,
            deployer: signed.pk.bytes().to_vec(),
            sig: signed.sig,
            sig_algorithm: signed.sig_algorithm.name().to_string(),
        }
    }

    #[test]
    fn attachments_are_part_of_the_signature() {
        // RCHIP #39: attachments live in the signed deploy data, so neither tampering with nor
        // stripping them can pass verification.
        let sd = signed_deploy_with_attachments(vec![vec![1, 2, 3]]);
        assert!(sd.verify_signature());

        let mut tampered = sd.clone();
        tampered.data.attachments = vec![vec![9, 9, 9]];
        assert!(!tampered.verify_signature());

        let mut stripped = sd;
        stripped.data.attachments.clear();
        assert!(!stripped.verify_signature());
    }

    #[test]
    fn attachments_round_trip_proto_and_json() {
        let deploy = DeployData {
            term: "Nil".to_string(),
            timestamp: 0,
            phlo_price: 1,
            phlo_limit: 1,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
            attachments: vec![vec![1, 2, 3], vec![]],
        };

        // The proto round-trip preserves the attachments (including an empty one).
        let bytes = <DeployData as Serialize<DeployData>>::encode(&deploy);
        assert_eq!(
            <DeployData as Serialize<DeployData>>::decode(&bytes).unwrap(),
            deploy
        );

        // JSON carries them as hex strings, and an ordinary deploy omits the field entirely.
        let json = serde_json::to_value(&deploy).unwrap();
        assert_eq!(json["attachments"], serde_json::json!(["010203", ""]));
        assert_eq!(serde_json::from_value::<DeployData>(json).unwrap(), deploy);

        let mut plain = deploy;
        plain.attachments.clear();
        assert!(serde_json::to_value(&plain)
            .unwrap()
            .get("attachments")
            .is_none());
    }

    #[test]
    fn total_phlo_charge_does_not_wrap_on_overflow() {
        let mut d = DeployData {
            attachments: Vec::new(),
            term: "Nil".to_string(),
            timestamp: 0,
            phlo_price: i64::MAX,
            phlo_limit: 2,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
        };
        assert_eq!(d.total_phlo_charge(), None);

        d.phlo_limit = 1;
        assert_eq!(
            d.total_phlo_charge(),
            Some(NonNegI64::try_from(i64::MAX).unwrap())
        );

        d.phlo_limit = 0;
        assert_eq!(d.total_phlo_charge(), Some(NonNegI64::zero()));

        // The sign, which this test did not cover until AUDIT C109: an overflow is not the only way a
        // charge can be unusable. A negative limit (or a negative price) is a *mint* if it reaches the
        // charge path, so it must be refused here, at the boundary, rather than at each caller.
        d.phlo_price = 1;
        d.phlo_limit = -100;
        assert_eq!(
            d.total_phlo_charge(),
            None,
            "a negative charge must not be representable"
        );

        d.phlo_price = -1;
        d.phlo_limit = 100;
        assert_eq!(
            d.total_phlo_charge(),
            None,
            "a negative price must not yield a usable charge"
        );
    }

    /// The refund's clamp, at the end the old code did not have (AUDIT C109). `refund_amount`'s doc
    /// claimed the result was "non-negative by construction" while `phlo_price` came straight off the
    /// wire; a negative price made a negative refund. Pinned at both ends now, because the claim is
    /// only worth making if a failing input can reach it.
    #[test]
    fn refund_amount_is_non_negative_for_every_input() {
        let mut d = DeployData {
            attachments: Vec::new(),
            term: "Nil".to_string(),
            timestamp: 0,
            phlo_price: 1,
            phlo_limit: 100,
            valid_after_block_number: 0,
            shard_id: "root".to_string(),
        };
        let mut processed = ProcessedDeploy {
            deploy: SignedDeployData {
                data: d.clone(),
                deployer: Vec::new(),
                sig: Vec::new(),
                sig_algorithm: String::new(),
            },
            cost: PCost { cost: 40 },
            deploy_log: Vec::new(),
            is_failed: false,
            system_deploy_error: None,
        };
        assert_eq!(i64::from(processed.refund_amount()), 60);

        // A negative price can no longer produce a negative refund.
        d.phlo_price = -1;
        processed.deploy.data = d;
        assert_eq!(i64::from(processed.refund_amount()), 0);

        // A negative limit cannot either, and must not borrow from the remaining-cost clamp.
        processed.deploy.data.phlo_price = 1;
        processed.deploy.data.phlo_limit = -100;
        assert_eq!(i64::from(processed.refund_amount()), 0);
    }

    /// **The equivocation evidence round-trips, and every field is checked on ingress** (AUDIT C200).
    ///
    /// The decode is the boundary between a proposer's bytes and a signature verification, so a field
    /// that is the wrong length has to be refused *here* rather than reaching a slice or an assert: a
    /// 31-byte "hash" that got through would be verified against a key it cannot belong to, and the
    /// verifier would answer `false` for a reason that has nothing to do with the offence. `decode` is
    /// also what makes `is_signed_by` total, since the hash it reads is a real one by then.
    #[test]
    fn equivocation_evidence_round_trips_and_refuses_a_malformed_field() {
        let evidence = EquivocationEvidence {
            block_hash: BlockHash::new([7u8; 32]),
            sender: Validator::new([9u8; 65]),
            seq_num: SeqNum::try_from(12).unwrap(),
            sig: vec![1, 2, 3],
            sig_algorithm: "secp256k1".to_string(),
        };
        assert_eq!(
            EquivocationEvidence::decode(&evidence.encode()).unwrap(),
            evidence,
            "the wire form carries every field, including the ones the verifier reads"
        );

        // A hash that is not 32 bytes: refused by the constructor, not by an assert further in.
        let short_hash = EquivocationEvidenceProto {
            block_hash: vec![7u8; 31],
            ..Default::default()
        };
        assert!(EquivocationEvidence::decode(&short_hash.encode_to_vec()).is_err());

        // A sender that is not a 65-byte key: the same, and this is the field `is_signed_by` reads
        // first, so a short one would otherwise be compared against a key of another length.
        let short_sender = EquivocationEvidenceProto {
            block_hash: vec![7u8; 32],
            sender: vec![9u8; 64],
            ..Default::default()
        };
        assert!(EquivocationEvidence::decode(&short_sender.encode_to_vec()).is_err());

        // Bytes that are not the message at all.
        assert!(EquivocationEvidence::decode(b"not evidence").is_err());
    }
}
